<?php 
$lan = array(
  "NoRecord" => "I record non esiste",
  "BackToBList" => "Torna alla lista dei rimbalzi",
  "NotFound" => "Non Trovato<br/>",
  "AddedToB" => "Aggiunto %s al conto dei bounce per l&acute;utente %s<br/>",
  "NotAddedToB" => "Non posso aggiungere %s al conto dei rimbalzi per l&acute;utente %s<br/>",
  "MadeUnconfirmed" => "Cambia l&acute;utente %s in Non Confermato<br/>",
  "MadeUserRText" => "Abilita l&acute;utente %s a ricevere testo<br/>",
  "DelUser" => "Cancella l&acute;utente %s<br/>",
  "DeletingB" => "St&oacute; eliminando il rimbalzo %s ..\n",
  "DoneAndLoading" => "..Fatto, carico il prossimo rimbalzo..",
  "NoSRecord" => "Questo record non esiste",
  "PossibleActions" => "Possibili Azioni:",
  "ForUser" => "Per l&acute;utente con email",
  "IncreaseB" => "Aumenta il conto dei rimbalzi con",
  "IncreaseBNote" => "(usa numeri negativi per diminuire)",
  "MarkAsUnconfirmed" => "Segna l&acute;utente come Non Confermato",
  "MarkAsUnconfirmedNote" => "(cos&iacute; puoi reinviare la richiesta di conferma)",
  "SetReceiveText" => "Abilita l&acute;utente a ricevere solo testo invece di HTML",
  "DelUser1" => "Elimina utente",
  "DelAndGo" => "Elimina questo rimbalzo e vai al successivo",
  "DoAbove" => "Fai quello specificato",
  "BounceDetails" => "Dettagli del Rimbalzo:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Stato",
  "Comment" => "Commento",
  "Header" => "Intestazione",
  "Body" => "Corpo",
  
  # new in 2.9.5
  'Regular Expression' => 'Espressione Regolare',
  'Action' => 'Azione',
  'Memo for this rule' => 'Memorizza questa regola',
  'Add new Rule' => 'Aggiungi una nuova regola',
  'Create New Rule based on this bounce' => 'Crea una nuova regola basata su questo rimbalzo',
);
?>