<?php

# file with common texts for translation

$lan = array(
  'logout' => 'Scollegati',
  'Main Page' => 'Pagina Principale',
  'user' => 'utente',
  'error' => 'Errore',
  'version' => 'versione',
  'powered by' => 'Creato da',
  'fatalerror' => 'Errore fatale',
  'warning' => 'Attenzione',
  'information' => 'Informazione',
  'help' => 'aiuto',
  'about' => 'informazioni su',
  'lists' => 'liste',
  'send a message' => 'Invia un messaggio',
  'users' => 'utenti',
  'manage users' => 'Gestione utenti',
  'messages' => 'Messaggi',
  'statistics' => 'Statistiche',
  'process queue' => 'Elabora la coda',
  'configure' => 'configura',
  'Subscribe Pages' => 'Pagina di sottoscrizione',
  'Send a prepared message' => 'Invia un messaggio preparato',
  'Prepare a message' => 'prepara un messaggio',
  'Templates' => 'Templates',
  'View Bounces' => 'Visualizza email ritorno',
  'Process Bounces' => 'Processa email di ritorno',
  'Eventlog' => 'log eventi',
  'Sunday' => 'Domenica',
  'Monday' => 'Luned&igrave;',
  'Tuesday' => 'Marted&igrave;',
  'Wednesday' => 'Mercoled&igrave;',
  'Thursday' => 'Gioved&igrave;',
  'Friday' => 'Venerd&igrave;',
  'Saturday' => 'Sabato',
  'January' => 'Gennaio',
  'February' => 'Febbraio',
  'March' => 'Marzo',
  'April' => 'Aprile',
  'May' => 'Maggio',
  'June' => 'Giugno',
  'July' => 'Luglio',
  'August' => 'Agosto',
  'September' => 'Settembre',
  'October' => 'Ottobre',
  'November' => 'Novembre',
  'December' => 'Dicembre',
  'Jan' => 'Gen',
  'Feb' => 'Feb',
  'Mar' => 'Mar',
  'Apr' => 'Apr',
  'shortMay' => 'Mag',
  'Jun' => 'Giu',
  'Jul' => 'Lug',
  'Aug' => 'Ago',
  'Sep' => 'Set',
  'Oct' => 'Ott',
  'Nov' => 'Nov',
  'Dec' => 'Dic',
  # from sendemaillib
  'sendingtextonlyto' => 'Invia testo solo a',
  'sendingmessage' => 'Invio Messaggi',
  'withsubject' => 'con argomento',
  'to' => 'a',
  'admininitfailure' => 'Inizializzazione autenticazione amministratore fallita',
  'yourpassword' => 'La tua password per phplist',
  'yourpasswordis' => 'La tua password &egrave;',
  'passwordsent' => 'La tua password &egrave; stata spedita via email',
  'cannotsendpassword' => 'Impossibile spedire la password',
  'ipchanged' => 'Il tuo indirizzo IP &egrave; cambiato. Per ragioni di sicurezza, ricollegati',
  'goodbye' => 'arrivederci',
  'goodmorning' => 'buongiorno',
  'goodafternoon' => 'buon pomeriggio',
  'goodevening' => 'buona sera',
  'safemodewarning' => 'In modalit&agrave; safe (safe mode), non tutto lavora come ci si aspetta',
  'magicquoteswarning' => 'Gli oggetti lavorano meglio quando PHP magic_quotes_gpc = <b>on</b>',
  'magicruntimewarning' => 'Gli oggetti lavorano meglio quando PHP magic_quotes_runtime = off',
  'noxml' => 'Stai provando a usare RSS, ma XML non è incluso nel tuo PHP',
  'warnopenbasedir' => 'restizioni su open_basedir restrictions sono attive, queste potranno essere causa di successive avvertenze',
  'warnattachmentrepository' => 'La repository degli allegati non esiste o non è scrivibile',
  'nofpdf' => 'Stai provando a usare il supporto PDF ma non è caricato FPDF',
  'warnpageroot' => 'La pageroot nella tua configurazione non corrisponde con la corrente locazione<br/>controlla il tuo archivio di configurazione.',
  'pagenotfoundinplugin' => 'La pagina non è stata trovata nei plugin',
  'notimplemented' => 'Funzione non ancora implementata',
  'noaccess' => 'Non hai sufficienti privilegi per accedere a questa pagina',
  'nohelpavailable' => 'Non è ancora stato implementato l\'aiuto per questo argomento:: ',
  'closewindow' => 'Chiudi questa finestra',
  'success' => 'successo',
  'failed' => 'fallito',
  'default login is' => 'Il login di Default &egrave;',
  'with password' => 'con password',
  'name' => 'Nome',
  'password' => 'Password',
  'enter' => 'Invio',
  'forgot password' => 'Password dimenticata?',
  'enter your email' => 'Inserisci la tua email',
  'send password' => 'Invia Password',
  'An image exists on the server, check this box to keep the existing one' => 'Una imagine esiste sul server, spunta questo box per conservare quello esistente',
  'View Image' => 'Visualizza immagini',
  'Upload new image' => 'Carica nuove immagini',
  'textline' => 'linea di testo',
  'textarea' => 'area di testo',
  'date' => 'data',
  'checkbox' => 'pulsante si spunta',
  'radio' => 'pulsante radio',
  'select' => 'selezione',
  'checkboxgroup' => 'gruppo di pulsanti di spunta',
  'unnamed list' => 'Lista anonima',
  'unknown' => 'Sconosciuto',
  'very little time' => 'Tempo piccolissimo',
  'A process for this page is already running and it was still alive' => 'Un processo per questa pagina è attualmente gi&agrave; in esecuzione ed &egrave; attualmente attivo',
  'seconds ago' => 'secondi passati',
  'We have been waiting too long, I guess the other process is still going ok' => 'Si st&agrave; attendento da troppo tempo, Si suppone vi sia un altro processo ancora in esecuzione',
  'Sleeping for 20 seconds, aborting will quit' => 'Attesa per 20 secondi, verr&agrave; abortito se se si esce',
  'No Image was found' => 'Nessuna immagine trovata',
  'messages' => 'Messaggi',
  'bounces' => 'Respinti',
  'bounce' => 'Respinto',
  'msg' => 'msg', # as in short for message
  'time' => 'ora',
  'sent' => 'inviato',
  'text' => 'testo',
  'html' => 'html',
  #
  # new for 2.9.5
  'delete user' => 'utente cancellato',
  'unconfirm user' => 'utente non confermato',
  'delete user and bounce' => 'cancella utente e messaggio respinto',
  'unconfirm user and delete bounce' => 'non confermare utente e cancella messaggio respinto',
  'blacklist user and delete bounce' => 'metti utente nella lista nera e cancella messaggio respinto',
  'delete bounce' => 'cancella messaggio respinto',
  'blacklist user' => 'Lista nera utenti',
  'manage bounces' => 'Gestisci i messaggi respinti',
  'perc' => '%',
  'invalid login from %s, tried logging in as %s' => 'login non valido da %s, prova a collegarti come %s',
  'successful password request from %s for %s' => 'richiesta password con successo da %s per %s',
  'failed password request from %s for %s' => 'richiesta password fallita da %s per %s',
  'login ip invalid from %s for %s (was %s)' => 'indirizzo IP non valido per il collegamento da %s per %s (era %s)',
  'invalidated login from %s for %s (error %s)' => 'login invalidato da %s per %s (errore %s)',
  'close' => 'chiudi',
  'open' => 'apri',
  'import is not available' => 'importazione non disponibile',

  # new for 2.10.0
  'Please wait, upgrading your database, do not interrupt' => 'Si prega attendere, aggiornamento database, non interrompere',
  'purgerss' => 'pulizia RSS',
  'Purge RSS items' => 'Pulizia articoli RSS',
  'In order to login, you need to enable cookies in your browser' => 'Per collegarsi, devi abilitare i cookies nel tuo browser',

  # added 2.10.2
  'globalvulnwarning' => 'Per la tua versione di PHP sono disponibili delle versioni maggiori di sicurezza.<br/>&egrave; consigliato aggiornarlo all\'ultima versione di PHP. <a href="http://www.hardened-php.net/globals-problem">Leggi...</a> informazioni sui problemi.',

);

?>
