<?php
$lan = array (
  'Your database is out of date, please make sure to upgrade' => 'Il vostro database è vecchio, Si prega aggiornarlo',
  'Your version' => 'Vostra versione',
  'Latest version' => 'Ultima versione',
  'phplist version' => '<a href=\"http://www.phplist.com\">phplist</a> versione',
  'Database has not been initialised' => 'Il Database non &egrave; correttamente inizializzato',
  'go to' => 'vai a',
  'Initialise Database' => 'Inizializza Database',
  'to continue' => 'per continuare',
  'A new version of PHPlist is available!' => 'Una nuova versione di PHPlist &egrave; disponibile!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'La nuova versione pu� avere degli aggiornamenti di sicurezza,<br/>si raccomanda di aggiornarle appena possibile',
  'View what has changed' => 'Visualizza le modifiche',
  'Download' => 'Scarica',
  'System Functions' => 'Funzioni di sistema',
  'Setup ' => 'Impostazioni ',
  'Check Database structure' => 'Controlla struttura del Database',
  'View the eventlog' => 'Visualizza il log degli eventi',
  'Configuration functions' => 'Funzioni di configurazione',
  'Configure Attributes' => 'Attributi di configurazione',
  'Control values for' => 'Valore di controllo per',
  'Configure Subscribe pages' => 'Configura pagine Sottoscrizione',
  'List and user functions' => 'Elenco e funzioni utente',
  'List the current lists' => 'Elenco delle correnti liste',
  'List all Users' => 'Elenca tutti gli Utenti',
  'Reconcile the user database' => 'Riconcilia il database degli utenti',
  'Import Users' => 'Importa Utenti',
  'Export Users' => 'Esporta Utenti',
  'Administrator functions' => 'Funzioni Aministratori',
  'Add, edit and remove Administrators' => 'Aggiunge, modifica e cancella Amministratori',
  'Configure attributes for administrators' => 'Configura attributi degli amministratori',
  'Message functions' => 'Funzioni dei Messaggi',
  'Configure Templates' => 'Configura Templates',
  'List all Messages' => 'Elenca tutti i messaggi',
  'Process the Message queue' => 'Processa la coda Messaggi',
  'RSS Functions' => 'Funzioni RSS',
  'Get RSS feeds' => 'Ricevi RSS feeds',
  'View RSS items' => 'Visualizza voci RSS',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Aggiorna',
  'Change your details (e.g. password)' => 'Cambia i tuoi dettagli (es. password)',
  'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Hai impostato TEST in config.php a 1, in questo modo vedi solo quello che hai spedito',
  'setup' => 'Impostazioni',
  'upgrade' => 'aggiorna',
  'dbcheck' => 'controlla db',
  'eventlog' => 'log eventi',
  'attributes' => 'attributi',
  'spage' => 'spage',
  'list' => 'elenco',
  'reconcileusers' => 'riconcilia utenti',
  'import' => 'importa',
  'export' => 'esporta',
  'admins' => 'amministra',
  'adminattributes' => 'attributi amministratore',
  'send' => 'spedisci',
  'templates' => 'templates',
  'processqueue' => 'coda processi',
  'processbounces' => 'processi rimbalzati',
  'getrss' => 'riceve rss',
  'viewrss' => 'visualizza rss',
  'admin' => 'ammnistra',
  'preparesend' => 'prepara spedizione',
  'sendprepared' => 'spedisci preparati',


);

?>