<?php
$lan = array (
  'Import emails from IMAP folders' => 'Importa indirizzi email da cartelline IMAP',
  'No lists available' => 'Nessuna lista disponibile',
  'Add a list' => 'Aggiungi una lista',
  'personal' => 'personale',
  'email' => 'email',
  'folder' => 'cartella',
  'date' => 'data',
  'can\'t connect' => 'non posso connettermi',
  'Processing' => 'elaborando',
  'messages' => 'messaggi',
  'done' => 'fatto',
  'imap_getmailboxes failed' => 'imap_getmailboxes fallito',
  'Please enter details of the IMAP account' => 'Per favore inserisci dettagli dell\'account IMAP',
  'Select the headers fields to search' => 'Scegli i campi intestazioni da cercare',
  'Select the lists to add the emails to' => 'Scegli le liste a cui aggiungere gli indirizzi email',
  'Adding users to list' => 'Aggiunta utenti alla lista',
  'Mark new users as HTML' => 'Segna nuovi utenti  come HTML',
  'If you check' => 'Se tu controlli',
  'Overwrite Existing' => 'Sovrapponi esistente',
  'information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'le informazioni riguardanti un utente nella base dati saranno sostituite dalle informazioi importate. Verr&agrave; usato l\'indirizzo email come campo chiave.',
  'Only use complete addresses' => 'Usa solo indirizzi completi',
  'addresses that do not have a real name will be ignored. Otherwise all emails will be imported.' => 'indirizzi senza nome reale verranno ignorati. Diversamente tutte le email verranno importate.',
  'If you choose' => 'Se tu scegli',
  'send notification email' => 'invia messaggio di notifica',
  'the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.' => 'agli utenti che stai aggiungendo verr&agrave; inviata una richiesta di conferma di iscrizione alla quale dovranno rispondere. Questo &egrave; raccomendato, perch&egrave; individua indirizzi email non validi.',
  'Send Notification email ' => 'Invia&nbsp;notifica&nbsp;email&nbsp;',
  'Make confirmed immediately' => 'Rendi confermato immediatamente',
  'import3info' => 'Ci sono due modi di aggiungere i nome degli utenti,
 o un attributo per l\'intero nome o due attributi, uno per il nome e uno per il cognome.
Se scegli \'due attributi\', il nome verr&agrave; spezzato a partire dal primo spazio.',
  'Use one attribute for name' => 'Usa un attributo per il nome',
  'Use two attributes for the name' => 'Usa due attributi per il nome',
  'Attribute one' => 'Attributo uno',
  'Create Attribute' => 'Crea attributo',
  'Attribute two' => 'Attributo due',
  'Cannot continue' => 'Non posso continuare',
  'ok' => 'ok',
  'failed' => 'fallito',
  'Processed' => 'Elaborato',
  'folders and' => 'cartelle e',
  'unique emails found' => 'trovati indirizzi email unici',
  'list' => 'lista',
  'lists' => 'liste',
  'new email was' => 'nuova email era',
  'new emails were' => 'le nuove email erano',
  'email was' => 'email era',
  'emails were' => 'email erano',
  'All the emails already exist in the database and are members of the' => 'Tutte le email esistono gi&agrave; nella base dati e sono parte di',
  'succesfully imported to the database and added to' => 'importate con successo e aggiunte a',
  'subscribed to the' => 'iscritto a',
  'emails already existed in the database' => 'le email esistevano gi&agrave; nella base dati',
  'Invalid Emails found.' => 'Trovate email non valide',
  'These records were added, but the email has been made up. You can find them by doing a search on' => 'Questi record sono stati aggiunti, ma le email sono state fatte. Puoi trovarli facendo una ricerca.',
  'These records were deleted. Check your source and reimport the data. Duplicates will be identified.' => 'Questi record sono stati cancellati. Controlla il tuo sorgente e reimporta i dati. I duplicati verranno identificati.',
  'No emails found' => 'Nessun email trovato',
  'Import some more emails' => 'Import altri email',
  'Server' => 'Server',
  'User' => 'Utente',
  'Password' => 'Password',
  'Continue' => 'Continua',
  'Process Selected Folders' => 'elabora cartelle selezionate',

);
?>
