<?php 
$lan = array(

  'add_list' => 'Aggiunge una lista', //duplicated in import1_text
  'cant_connect' => 'non &egrave; possibile collegarsi al database remoto',
  'no_users_to_copy' => 'nessun utente da copiare, il prefisso &egrave; corretto?',
  'remote_server' => 'Inserisci i dettagli del Server remoto',
  'server' => 'Server:',
  'user' => 'Utente:',
  'passwd' => 'Password:',
  'database' => 'Nome Database:',
  'table_prefix' => 'Prefisso Tabella:',
  'usertable_prefix' => 'Prefisso tabella utenti:',
  'select_lists' => 'Seleziona la lista a cui aggiungere le emails',
  'copy_lists' => 'copia le liste da un server remoto (Le liste saranno confrontate tramite nome)',
  'users_as_html' => 'Spunta nuovo utente come HTML:',
  'info_overwrite_existing' => 'Se spuntato "Sovrascrivi Esistenti", le informazioni relative all\'utente nel database saranno sostituite dalle informazioni importate. Gli utenti saranno confrontati tramite email.',
  'overwrite_existing' => 'Sovrascrivi Esistenti:',
  'connecting_remote' => 'Esegue connessione con database remoto',
  'getting_data' => 'Ottieni i dati da ',
  'remote_version' => 'Versione Remota &egrave;',
  'remote_has' => 'Versione Remota ha',
  'users' => 'utenti',
  'lists' => 'liste',
  'copying_lists' => 'copiare liste',
  'list' => 'Lista',
  'exists_locally' => 'esiste localmente',
  'created_locally' => 'creata localmente',
  'remote_list' => 'lista remota',
  'not_created' => 'non creata',
  'copying_attribs' => 'copiare attributi',
  'attrib' => 'Attributi',
  'copying_users' => 'Copiare utenti',
  'overwrite_local' => 'sovrascrivere dati locali',
  'keep_local' => 'mantenere dati locali',
  'new_user' => '&egrave; un nuovo utente',
  'no_mapped_attrib' => 'Errore, non rilevati attributi per',
  'no_local_list' => 'Errore, nessuna lista definita per',
  'No lists available' => 'Nessuna lista disponibile',
  'Done' => 'Fatto',
  'new users' => 'nuovi utenti',
  'and' => 'e',
  'existing users' => 'utenti esistenti',
  'continue' => 'Continua',

);
?>
