<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Non hai privilegi sufficienti per visualizzare questa pagina',
  'Add a user' => 'Aggiungi un utente',
  'add user' => 'Aggiunta utente',
  'Members of' => 'Membro di',
  'Tag all users in this page' => 'Seleziona tutti gli utenti di questa pagina',
  'back to this list' => 'ritorna a questa lista',
  'Download users on this list as a CSV file' => 'Scarica gli utenti di questa lista su un file CSV',
  'Please enter a listid' => 'Inserisci l\'id della lista',
  'Processing' => 'In lavorazione',
  'users were moved to' => 'utenti spostati in',
  'users were copied to' => 'utenti copiati in',
  'users were deleted from this list' => 'utenti cancellati da questa lista',
  'Users found, click add to add this user' => 'Utenti trovati, clicca su aggiungi per aggiungere questo utente',
  'Add' => 'Aggiungi',
  'No user found with that email' => 'Nessun utente trovato con quella email',
  'Inserting user' => 'Inserimento utente',
  'User added' => 'Utente aggiunto',
  'Deleting' => 'Cancellazione',
  'Done' => 'Fatto',
  'Users on this list' => 'Utenti in questa lista',
  'Listing user' => 'Lista utenti da',
  'to' => 'a',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Lista utenti da 1 a 50',
  'Members' => 'Membri',
  'confirmed' => 'confermato',
  'tag' => 'tag',
  'del' => 'cancella',
  'Delete'=>'Cancella',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss freq',
  'last sent' => 'ultimo inviato',
  'What to do with "Tagged" users' => 'Cosa fare con gli utenti "Selezionati"',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Vengono processati solo gli utenti di questa pagina il checkbox "Tag" attivo',
  'delete' => 'Cancella',
  'move' => 'Sposta',
  'copy' => 'Copia',
  'nothing' => 'Niente',
  'to' => 'a', # as in destination
  'from this list' => 'da questa lista',
  'What to do with all users' => 'Cosa fare con tutti gli utenti',
  'This will process all users on this list' => 'Saranno processati tutti gli utenti di questa lista',
  'do it' => 'procedi',
  
  
);
?>
