<?php
$lan = array(
 'Please select a message to display' => 'Seleziona un messaggio da visualizzare',
 'Attachments for this message' => 'Allegati di questo messaggio',
 'No attachments' => 'Nessun allegato',
 'Filename' => 'Nome del file',
 'Size' => 'Dimensione',
 'Mime Type' => 'Tipo Mime',
 'Description' => 'Descrizione',
 'Lists this message has been sent to' => 'Liste a cui questo messaggio &egrave; stato inviato a',
 'None yet' => 'Non ancora',
 'Send this (same) message to (a) new list(s)' => 'Invia questo (stesso) messaggio ad o pi&uacute; nuove liste',
 'List is Active' => 'Lista attiva',
 'List is not Active' => 'Lista non attiva',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Note:</b> questo messaggio &egrave; stato gi&aacute; inviato a tutte le liste. Per rimandarlo ai nuovi utenti usa la funzione "Riaccoda".',
 'Resend' => 'Invia di nuovo',
 'id' => 'id',
 'subject' => 'soggetto',
 'fromfield' => 'campo da',
 'tofield' => 'campo a',
 'replyto' => 'rispondi a',
 'message' => 'messaggio',
 'textmessage' => 'messaggio testuale',
 'footer' => 'firma',
 'entered' => 'inserito',
 'modified' => 'modificato',
 'embargo' => 'posticipato',
 'repeatinterval' => 'intervallo ripetizione',
 'repeatuntil' => 'ripeti fino',
 'status' => 'stato',
 'userselection' => 'selezione utente',
 'sent' => 'inviato',
 'htmlformatted' => 'formato html',
 'sendformat' => 'formato invio',
 'template' => 'template',
 'processed' => 'processato',
 'astext' => 'come testo',
 'ashtml' => 'come codice html',
 'astextandhtml' => 'testo semplice e html',
 'aspdf' => 'come pdf',
 'astextandpdf' => 'come testo e pdf',
 'viewed' => 'visto',
 'bouncecount' => 'numero email di ritorno',
 'sendstart' => 'inizio invio',
 'rsstemplate' => 'RSS template',
 'owner' => 'proprietario',

 # new in 2.10.1
 'edit this message' => 'Modifica questo messaggio',
);
?>
