<?php
$lan = array (
 'noaccess' => 'Nessun messaggio, o non hai accesso a questo messaggio',
 'htmlusedwarning' => 'Attenzione: hai indicato il contenuto come non html, ma c\'era dentro qualche tag html. Questo pu&ograve; causare errori',
 'adding' => 'Aggiunta',
 'longmimetype' => 'Tipo Mime &egrave; pi&ugrave; lungo di 255 caratteri, questo &egrave; un problema',
 'addingattachment' => 'Allegato aggiunto',
 'uploadfailed' => 'File caricato non ricevuto correttamente, il file &egrave; vuoto',
 'saved' => 'Messaggio salvato',
 'added' => 'Messaggio aggiunto',
 'queued' => 'Messaggio accodato per l\'invio',
 'processqueue' => 'Elabora la coda messaggi',
 'errorsubject' => 'Spiacente,  hai usato caratteri non validi nel campo Oggetto.',
 'errorfrom' => 'Spiacente,  hai usato caratteri non validi nel campo Da',
 'enterfrom' => 'Per favore inserisci la linea da',
 'entermessage' => 'Per favore inserisci un messaggio',
 'entersubject' => 'Per favore inserisci un oggetto',
 'duplicateattribute' => 'Errore: puoi usare un attributo per una regola solamente.',
 'selectlist' => 'Per favore scegli  la(e) lista(e) a cui mandare il messaggio',
 'notargetemail' => 'Nessun indirizzo di destinazione elencato per la prova',
 'emailnotfound' => 'Indirizzo email per l\'invio della prova non trovato ',
 'sentemailto' => 'Invia l\'email di prova a',
 'removedattachment' => 'Allegato rimosso',
 'existingcriteria' => 'criteri esistenti',
 'remove' => 'rimuovi',
 'calculating' => 'calcolo in corso',
 'calculate' => 'calcolati',
 'content' => 'contenuto',
 'format' => 'formato',
 'attach' => 'allega',
 'scheduling' => 'programmazione',
 'criteria' => 'criteri',
 'lists' => 'liste',
 'unsavedchanges' => 'Attenzione, non hai salvato\\nClicca OK per continuare o Annulla per stare in questa pagina\\n in modo che puoi salvare i cambiamenti.',
 'whatisprepare' => 'Cos\'&egrave; preparare un messaggio',
 'subject' => 'oggetto',
 'fromline' => 'Linea Da',
 'embargoeduntil' => 'Non inviabile (embargo) fino a',
 'repeatevery' => 'Ripeti il messaggio ogni',
 'norepetition' => 'nessuna ripetizione',
 'hour' => 'Ora',
 'day' => 'Giorno',
 'week' => 'Settimana',
 'repeatuntil' => 'Ripeti fino',
 'autodetect' => 'Auto rileva',
 'sendas' => 'Invia come',
 'html' => 'HTML',
 'text' => 'testo',
 'pdf' => 'PDF',
 'textandhtml' => 'Testo e HTML',
 'textandpdf' => 'Testo e PDF',
 'usetemplate' => 'Usa modello',
 'selectone' => 'scegli uno',
 'rssintro' => 'Se vuoi usare questo messaggio come modello per mandare RSS 
   scegli la frequenda da usare e utilizza [RSS] nel messaggio 
dove si vuole che appaia la lista.',
 'none' => 'nessuno',
 'message' => 'Messaggio',
 'expand' => 'espandi',
 'plaintextversion' => 'Versione del messaggio in formato testo ',
 'messagefooter' => 'Pedice messaggio',
 'messagefooterexplanation' => 'Usa <b>[UNSUBSCRIBE]</b> per inserire l\'indirizzo URL personale di disiscrizione per ogni utente.
   <br/>Usa <b>[PREFERENCES]</b> per inserire l\'indirizzo URL personale per permettere a ogni utente di cambiare le proprie preferenze.',
 'addattachments' => 'Aggiungi allegati al tuo messaggio',
 'uploadlimits' => 'Il caricamento ha i seguenti limiti impostati dal server',
 'maxtotaldata' => 'Quantit&agrave; massima di dati da inviare al server',
 'maxfileupload' => 'Grandezza massima per ogni singolo file',
 'currentattachments' => 'Allegati correnti',
 'filename' => 'nome del file',
 'desc' => 'descr',
 'size' => 'grandezza',
 'file' => 'file',
 'del' => 'canc',
 'newattachment' => 'Nuovo allegato',
 'addandsave' => 'Aggiungi (e salva)',
 'pathtofile' => 'Percorso del file sul server',
 'attachmentdescription' => 'Descrizione dell\'allegato',
 'delchecked' => 'Cancellazione segnata',
 'sendtestmessage' => 'Invia messaggio di prova',
 'toemailaddresses' => ' all\'indirizzo(i) email',
 'sendtestexplain' => '(indirizzi separati da virgola - tutti devono essere utenti)',
 'criteriaexplanation' => '        <p><b>scegli i criteri per questo messaggio:</b>
       <ol>
       <li>per usare un criterio, controlla il box vicino ad esso
       <li>quindi spunta il bottone radio vicino all\'attributo che vuoi usare
       <li>quindi scegli i valori degli attributi a cui vuoi inviare il messaggio
       <i>Nota:</i> i messaggi verranno inviati alle persone che rispondono a  <i>Criterio 1</i> <b>E</b> <i>Criterio 2</i> ecc.
       </ol>
       ',
 'criterion' => 'Prova di verifica',
 'usethisone' => 'Usa questo',
 'or' => 'o',
 'is' => '&egrave;',
 'isnot' => 'non &egrave;',
 'isbefore' => '&egrave; prima',
 'isafter' => '&egrave; dopo',
 'nocriteria' => 'Al momento non ci sono attributi disponibili da usare per l\'invio di un messaggio. Il messaggio andr&agrave; a qualsiasi utente della lista(e) scelta(e)',
 'checked' => 'Segnato ',
 'unchecked' => 'non segnato',
 'buggywithie' => 'Attenzione, questa funzionalit&agrave; &egrave; difettosa e inaffidabile con IE (Internet Explorer).\\nSarebbe meglio usare Mozilla, Firefox o Opera\\nAlternativamente disattiva STACKED_ATTRIBUTE_SELECTION nel tuo file di configurazione.',
 'matchallrules' => 'Trova corrispondenze con tutte queste regole',
 'matchanyrules' => 'Trova corrispondenze con qualsisi regola',
 'addcriterion' => 'Aggiungi una prova di verifica',
 'saveasdraft' => 'Salva i messaggi come bozza',
 'savechanges' => 'Salva cambiamenti',
 'selectattribute' => 'scegli attributo',
 'dd-mm-yyyy' => 'dd-mm-yyyy',
 'selectlists' => 'Prego scegli le liste a cui vuoi mandarlo',
 'alllists' => 'Tutte le liste',
 'listactive' => 'La lista &egrave; attiva',
 'listnotactive' => 'La lista NON &egrave; attiva',
 'selectexcludelist' => 'scegli le liste da escludere',
 'excludelistexplain' => 'Il messaggio andr&agrave; agli utenti che sono membri delle liste sopra,
   a meno che non siano membri di una delle liste che hai scelto qui.',
 'nolistsavailable' => 'Spiacente, non ci sono liste disponibili al momento.',
 'sendmessage' => 'Manda il messaggio alle liste selezionate',
 'warnnopearhttprequest' => 'Stai provando a inviare un URL remoto, ma PEAR::HTTP/Request non &egrave; disponibile, quindi l\'invio fallir&abrave;',
 'Misc' => 'Varie',
 'email to alert when sending of this message starts' => 'email da avvertire quando l\'invio di questo messaggio comincia:',
 'email to alert when sending of this message has finished' => 'email da avvertire quando l\'invio di questo messaggio &egrave; finito:',
 'separate multiple with a comma' => '(separa pi&ugrave; email con una virgola)',
 'operator' => 'operatore',
 'values' => 'valori',
 '%d users apply' => 'ci sono %d utenti ',
 'reload' => 'ricarica',
);
?>
