<?php
$lan = array (
  'General Information' => 'Informazioni generali',
  'Title' => 'Titolo',
  'Title of this set of lists' => 'Titolo di questo insieme di liste',
  'Please indicate how often you want to receive messages' => 'Indica quanto spesso vuoi ricevere messaggi',
  'Don\'t offer choice, default to <b>text</b>' => 'Non offrire scelte,  scelta predefinita: <b>testo</b>',
  'Don\'t offer choice, default to <b>HTML</b>' => 'Non offrire scelte,  scelta predefinita: <b>HTML</b>',
  'Don\'t display email confirmation' => 'Non visualizzare la conferma email',
  'Intro' => 'Intro',
  'Header' => 'Intestazione',
  'Footer' => 'Pi&egrave; pagina',
  'Thank you page' => 'Pagina di ringraziamento',
  'Text for Button' => 'Testo del bottone',
  'HTML Email choice' => 'Scelta email HTML ',
  'Offer checkbox for text' => 'Offri checkbox per testo',
  'Offer checkbox for HTML' => 'Offri checkbox per HTML',
  'Radio buttons, default to text' => 'Bottoni Radio, predefinito il testo',
  'Radio buttons, default to HTML' => 'Bottoni Radio, predefinito HTML',
  'Display Email confirmation' => 'Visualizza conferma Email',
  'Display email confirmation' => 'Visualizza conferma Email',
  'Message they receive when they subscribe' => 'Messaggio che ricevono quando si iscrivono',
  'Message they receive when they confirm their subscription' => 'Messaggio che ricevono quando confermano l\'iscrizione',
  'Subject' => 'Oggetto',
  'Message' => 'Messaggio',
  'Select the attributes to use' => 'Scegli gli attributi da usare',
  'No lists available, please create one first' => 'Nessuna lista disponibile, per favore creane una prima',
  'Attribute' => 'Attributo',
  'Check this box to use this attribute in the page' => 'Spunta questo box per usare questo attributo nella pagina',
  'Type' => 'Tipo',
  'Default Value' => 'Valore predefinito',
  'Order of Listing' => 'Ordine in elenco',
  'Is this attribute required?' => 'Questo attributo &egrave; obbligatorio?',
  'RSS settings' => 'Impostazioni RSS',
  'Intro Text' => 'testo di introduzione ',
  'Offer option to receive' => 'Offri opzioni per ricevere',
  'Daily' => 'Giornaliero',
  'default' => 'predefinito',
  'Weekly' => 'Settimanale',
  'Monthly' => 'mensile',
  'Select the lists to offer' => 'Scegli le liste da offrire',
  'Owner' => 'Proprietario',
  'Save Changes' => 'Salva cambiamenti',
  'Save and Activate' => 'Salva e attiva',
  'Save and Deactivate' => 'Salva e disattiva',

);
?>