<?php
$lan = array (
  'No such template' => 'Non questo modello',
  'Images stored' => 'Immagini immagazzinate',
  'No images found' => 'Nessuna immagine trovata',
  'Image' => 'Immagine',
  'not full URL' => 'Non URL completa',
  'does not exist' => 'non esiste',
  'Not a full URL:' => 'Non una URL completa:',
  'No Title' => 'Nessun titolo',
  'Template does not contain the [CONTENT' => 'Il modello non contiene  il segnaopsto [CONTENT] ',
  'Template saved' => 'Modello salvato',
  'Images' => 'Immagini',
  'Below is the list of images used in your template. If an image is currently unavailable, please upload it to the database.' => 'In basso trovi la lista delle immagini usate nel tuo modello. Se al momento un immagine non &grave; disponibile, per favore caricala nel sistema.',
  'This includes all images, also fully referenced ones, so you may choose not to upload some. If you upload images, they will be included in the emails that use this template.' => 'Questo include tutte le immagini, anche quelle interamente referenziate, quindi potrersti evitare di caricarne alcune. Se carichi immagini, esse verranno incluse nelle email che fanno uso di questo modello.',
  'Image name:' => 'Nome immagine:',
  'times used' => 'n. volte usata',
  'Template does not contain local images' => 'Il modello non contiene immagini locali',
  'Some errors were found, template NOT saved!' => 'Alcuni errori sono stati trovati, modello NON salvato!',
  'List of Templates' => 'Elenco dei modelli',
  'Title of this template' => 'Titolo di questo modello',
  'Content of the template.' => 'Contenuto di questo modello',
  'The content should at least have <b>[CONTENT' => 'Il contenuto dovrebbe almeno avere <b>[CONTENT]</b> da qualche parte.',
  'Check that all links have a full URL' => 'Controlla che tutti i collegamenti abbiano un URL completo.',
  'Check that all images have a full URL' => 'Controlla che tutte le immagini abbiano un URL completo.',
  'Check that all external images exist' => 'Controlla l\'esistenza di tutte le immagini esterne',
  'Save Changes' => 'Salva i cambiamenti',
  'Save Images' => 'Salva immagini',
  'You can upload a template file or paste the text in the box below' => 'Puoi caricare un file modello o incollare il testo nel riquadro in basso.',
  'Template file.' => 'File modello.',

);
?>
