<?

# language dependent text used in the interface for users (not admin)
# Czech translation by Ota Lunak ota.lunak@quick.cz
# alternative coding iso-8859-2
# V. 22.03.06-01 /PHPlist  2.10.2

$strCharSet             = 'Windows-1250';
$strName                = 'Jméno';
$strAddress             = 'Adresa';
$strEmail               = 'Email';
$strTown                = 'Mìsto';
$strPostcode            = 'PSÈ';
$strSubscribeInfo       = 'Zaregistrujte se k odbìru nìkterého informaèního zpravodaje ze seznamu níže';
$strRequired            = '(Vyžadované pole)';
$strSubscribeTitle      = 'Zaregistrujte se v nìkterém info seznamu';
$strPleaseSelect        = 'Vyberte seznam, kde se chcete zaregistrovat, prosím';
$strSubmit              = 'Zaregistrovat se do vybraných info seznamù;';
$strNotAvailable        = 'Litujeme, ale žádný info seznam není k dispozici';
$strEnterName           = 'Zadejte Vaše jméno, prosím';
$strEnterEmail          = 'Zadejte Vaši emailovou adresu, prosím';
$strInvalidHostInEmail  = 'Vaše emailová adresa nebyla ovìøena. Zkontrolujte ji, prosím';
$strEnterList           = 'Vyberte info seznam, prosím';
$strPleaseEnter         = 'Zadejte prosím ';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Dìkujeme za registraci!';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Obratem zasíláme Vaši registraci potvrzující email na adresu [email].';
$strEmailFailed					= 'Litujeme, ale registraci potvrzující email se nepodaøilo odeslat. Zkuste znovu, prosím.';
$strUnsubscribeTitle    = 'Odhlášení z registrace odbìru zpravodaj&#367;.';
$strUnsubscribeDone     = 'Potvrzující email o odhlášení z odbìru zpravodajù bude obratem odeslán.';
$strBack                = 'Zpìt';
$strUnsubscribeInfo     = 'Zrušit registraci v nìkterém z info seznam&#367;';
$strContinue            = 'Pokraèovat';
$strUnsubscribeSelect   = 'Vyberte prosím seznam, ze kterého se chcete odhlásit';
$strAllLists            = 'Všechny info seznamy';
$strNoLists             = 'Žádný ze seznamù';
$strUnsubscribeRequestForReason = 'We are sorry to find you are not any longer interested in our newsletter. To help us improve our services, we would be grateful if you could tell us why:';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page is to stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strNoListsFound        = 'Litujeme, ale tato adresa v databázi neexistuje.';
$strResubmit            = 'Znovu potvrdit emailovou adresu';
$strUnsubscribeSubmit   = 'Zrušit registraci ve vybraných info seznamech';
$strValuesMissing       = 'Chybí následující požadované údaje';
$strConfirmInfo         = 'Dìkujeme za potvrzení odbìru zpravodajù zobrazených níže';
$strConfirmTitle        = 'Stránka potvrzení odbìru';
$strUserNotFound        = 'Uživatel nenalezen';
$strUserAlreadyInitialised = 'Litujeme, ale Vaše heslo již bylo nastaveno';
$strConfirmFailInfo     = 'Litujeme, ale pøi potvrzení došlo k chybì, specifikované níže';
$strPreferHTMLEmail     = 'Preferuji HTML formát';
$strPreferTextEmail     = 'Preferuji textový formát';
$strPreferredFormat		= 'Preferovaný formát emailu:';
$strTex					= 'Text';
$strHTM					= 'HTML';
$strPreferencesTitle    = 'Inovovat preference';
$strPreferencesInfo     = 'Prosím, potvrïte správnost informace kliknutím na tlaèítko "Inovace"';
$strUpdatePreferences   = 'Inovace';
$strPreferencesEmailChanged = 'Vaše emailová adresa je zmìnìna. Kliknìte na odkaz v potvrzujícím emailu, který obdržíte, a potvrïte registraci, prosím.';
$strYouAreBlacklisted = 'Váše adresa je na našem "Black Listu", což znamená, že jste již nechtìli obtìžovat. <br/>
Abychom Vás opìt mohli zaøadit na seznam našich odbìratelù, musíte kontaktovat našeho administrátora. ';
$strPreferencesNotificationSent = 'Obdržíte email, obsahující zmìny';
$strPreferencesUpdated = 'Dìkujeme, inovovali jsme Vaše data.';
$strClickHere          = 'Kliknìte zde';
$strThisLink           = '<-- zde';
$strToUnsubscribe      = 'Zrušit pøedplatné mùžete ';
$strToUpdate           = 'Inovovat vaše preference mùžete ';
$strSendHTML           = 'Zaslat HTML formát';
$strYes                = 'Ano';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odhlásit';
$strAllMailinglists    = 'Všechny zpravodaje';
$strAttachmentIntro	   = 'Tato zpráva obsahuje pøílohy, které mùžete otevøít pomocí prohlížeèe:';
$strLocation		   = 'Místo';
$strFrequency		   = 'Jak èasto Vám posíláme zprávy';
$strHourly			   = 'Každou hodinu';
$strDaily			   = 'Dennì';
$strWeekly			   = 'Týdnì';
$strMonthly			   = 'Mìsíènì';
$strChoosePassword 	   = 'Zadejte heslo, prosím';
$strConfirmPassword    = 'Potvrïte heslo, prosím';
$strEnterPassword	   = 'Zadejte heslo, prosím';
$strForgotPassword	   = 'Heslo zapomenuto';
$strPassword		   = 'Heslo';
$strPassword2		   = 'Potvrïte heslo';
$strPasswordsNoMatch   = 'Hesla se neshodují';
$strEmailsNoMatch      = 'Zadaná emailová adresa se neshoduje';
$strInvalidPassword	   = 'CHYBA: Neplatný email, nebo heslo';
$strPasswordSent 	   = 'Heslo Vám bylo zasláno elektronickou poštou.';
$strPasswordRemindSubject = 'Heslo pro zpravodaje: ';
$strPasswordRemindMessage = 'Heslo je: ';
$strPasswordRemindInfo = 'Pro zaslání hesla elektronickou poštou, vložte svojí  email adresu a kliknìte na "'.$strForgotPassword.'" klávesu.';
$strLogin			   = 'Pøihlásit';
$strLoginTitle 		   = 'Zadejte, prosím, Vaše heslo a emailovou adresu.';
$strLoginInfo		   = 'Tato stránka vyžaduje pøístupové heslo. Zadejte, prosím, Vaše heslo a emailovou adresu.';
$strPersonalLocationInfo = '
	<p>Tato stránka vyžaduje identifikaci, která je obsažena v každé emailové záslice, kterou zasíláme.<br/>
  Pokud jste po kliknutí na odkaz získal tuto chybovou hlášku, ujistìte se, prosím, že celý odkaz je na jediném øádku a je úplný.
  Nìkdy je poštovním klientem odkaz zalomen na více øádkù.</p>
  <p>Pokud odkaz nemáte, zadejte, prosím, svoji emailovou adresu, a obdržíte potvrzovací email.
  zadejte, prosím, svoji emailovou adresu a kliknìte na "Pokraèovat".';
$strPersonalLocationSent = '<h1>Výbornì! V nìkolika minutách obdržíte na vloženou adresu potøebné informace. Dìkujeme.</h1>';
$strUserExists   = '<br/>Uživatel se zadanou adresou existuje a liší se heslo';
$strUserExistsExplanationStart = '<br/>Chcete-li získat Vaše heslo, kliknìte ';
$strUserExistsExplanationLink = '<-- zde';
$strUserExistsExplanationEnd = ' a budete pøesmìrováni';
$strForwardTitle = 'Pøeposlat zprávu jiné osobì';
$strForwardSubtitle = 'Pøeposlat zprávu s pøedmìtem ';
$strForwardEnterEmail = 'Zadejte emailovou adresu, na kterou chcete zprávu pøeposlat';
$strForwardSuccessInfo ='Zpráva pøeposlána';
$strForwardFailInfo = 'Zpráva nepøeposlána, odeslání selhalo';
$strForwardAlreadyDone = 'Zpráva úspìšnì pøeposlána na zadanou adresu';
$strForwardFooter = 'Zpráva pøeposlána z adresy [FORWARDEDBY].
  Pøeposlání neznamená registraci k odbìru zpravodaje. Pokud se chcete zaregistrovat, kliknìte na';
$strForward = 'Pøeposlat';
$strFwd = 'Fwd'; # short version of forward for email subject
?>


