<?

# language dependent text used in the interface for users (not admin)
# Czech translation by Ota Lunak ota.lunak@quick.cz
# alternative coding iso-8859-2
# V. 11.07.03-01 /PHPlist 2.3.4

$strCharSet             = 'Windows-1250';
$strName                = 'Jméno';
$strAddress             = 'Adresa';
$strEmail               = 'Email';
$strTown                = 'Mìsto';
$strPostcode            = 'PSÈ';
$strSubscribeInfo       = 'Zaregistrujte se k odbìru nìkterého informaèního zpravodaje ze seznamu níže';
$strRequired            = '(Vyžadované pole)';
$strSubscribeTitle      = 'Zaregistrujte se v nìkterém info seznamu';
$strPleaseSelect        = 'Vyberte seznam, kde se chcete zaregistrovat, prosím';
$strSubmit              = 'Zaregistrovat se do vybraných info seznam&#367;';
$strNotAvailable        = 'Litujeme, ale žádný info seznam není k dispozici';
$strEnterName           = 'Zadejte Vaše jméno, prosím';
$strEnterEmail          = 'Zadejte Vaši emailovou adresu, prosím';
$strInvalidHostInEmail  = 'Vaše emailová adresa nebyla ovìøena. Zkontrolujte ji, prosím';
$strEnterList           = 'Vyberte info seznam, prosím';
$strPleaseEnter         = 'Zadejte prosím ';
$strThanks              = 'Dìkujeme za registraci!';
$strThanksX             = '[FIRST NAME]> Dìkujeme za registraci!';
$strEmailConfirmation   = 'Obratem zasíláme Vaši registraci potvrzující email.';
$strEmailFailed					= 'Litujeme, ale registraci potvrzující email se nepodaøilo odeslat. Zkuste znovu, prosím.';
$strUnsubscribeTitle    = 'Odhlášení z registrace odbìru zpravodaj&#367;.';
$strUnsubscribeDone     = 'Potvrzující email o odhlášení z odbìru zpravodajù bude obratem odeslán.';
$strBack                = 'Zpìt';
$strUnsubscribeInfo     = 'Zrušit registraci v nìkterém z info seznam&#367;';
$strContinue            = 'Pokraèovat';
$strUnsubscribeSelect   = 'Vyberte prosím seznam, ze kterého se chcete odhlásit';
$strAllLists            = 'Všechny info seznamy';
$strNoLists             = 'Žádný ze seznamù';
$strNoListsFound        = 'Litujeme, ale tato adresa v databázi neexistuje.';
$strResubmit            = 'Znovu potvrdit emailovou adresu';
$strUnsubscribeSubmit   = 'Zrušit registraci ve vybraných info seznamech';
$strValuesMissing       = 'Chybí následující požadované údaje';
$strConfirmInfo         = 'Dìkujeme za potvrzení odbìru zpravodajù zobrazených níže';
$strConfirmTitle        = 'Stránka potvrzení odbìru';
$strUserNotFound        = 'Uživatel nenalezen';
$strConfirmFailInfo     = 'Litujeme, ale pøi potvrzení došlo k chybì, specifikované níže';
$strPreferHTMLEmail     = 'Preferuji HTML formát';
$strPreferTextEmail     = 'Preferuji textový formát';
$strPreferredFormat			= 'Preferovaný formát emailu:';
$strText 								= 'Text';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Inovovat preference';
$strPreferencesInfo     = 'Prosím, potvrïte správnost informace kliknutím na tlaèítko "Inovace"';
$strUpdatePreferences   = 'Inovace';
$strPreferencesEmailChanged = 'Vaše emailová adresa je zmìnìna. Kliknìte na odkaz v potvrzujícím emailu, který obdržíte, a potvrïte registraci, prosím.';
$strPreferencesNotificationSent = 'Obdržíte email, obsahující zmìny';
$strPreferencesUpdated = 'Dìkujeme, inovovali jsme Vaše data.';
$strClickHere          = 'Kliknìte zde';
$strThisLink           = '<-- zde';
$strToUnsubscribe      = 'Zrušit pøedplatné mùžete ';
$strToUpdate           = 'Inovovat vaše preference mùžete ';
$strSendHTML           = 'Zaslat HTML formát';
$strYes                = 'Ano';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odhlásit';
$strAttachmentIntro		 = 'Tato zpráva obsahuje pøílohy, které mùžete otevøít pomocí prohlížeèe:';
$strLocation					 = 'Místo';
$strFrequency					 = 'Jak èasto Vám posíláme zprávy';
$strHourly						 = 'Každou hodinu';
$strDaily							 = 'Dennì';
$strWeekly						 = 'Týdnì';
$strMonthly						 = 'Mìsíènì';
$strChoosePassword 		 = 'Zadejte heslo, prosím';
$strConfirmPassword 	 = 'Potvrïte heslo, prosím';


?>