<?

# language dependent text used in the interface for users (not admin)
# translation by Steen Rabøl <srabol@mail.tele.dk>
# translated for version 1.1.6

$strName                = 'Navn';
$strAddress             = 'Adresse';
$strEmail               = 'Email';
$strTown                = 'By';
$strPostcode            = 'Postnr';
$strSubscribeInfo       = 'Tilmeld dig til en eller flere af vores postlister ved at udfylde formularen nedenfor.';
$strRequired            = 'Oligatorisk felt';
$strSubscribeTitle      = 'Tilmeld dig til en af vores postliste';
$strPleaseSelect        = 'Vælg de postlister du ønsker at tilmelde dig';
$strSubmit              = 'Tilmed de valgte postlister';
$strNotAvailable        = 'Beklager, der er ingen postlister tilgængelige';
$strEnterName           = 'Indtast dit navn';
$strEnterEmail          = 'Indtast din EMail adresse';
$strEnterList           = 'Vælg en postliste du ønsker at tilmelde dig';
$strThanks              = 'Tak fordi du har tilmeldt dig til en af vore postlister.';
$strEmailConfirmation   = 'Du vil inden for meget kort tid modtage en EMail med bekrægtigelse på de postlister du har tilmeldt dig';
$strUnsubscribeTitle    = 'Afmeld dig fra en af vores postlister';
$strUnsubscribeDone     = 'Du er blevet afmeldt fra de valgte postlister. Du vil modtage en bekræftigelse inden kort tid.';
$strBack                = 'Tilbage';
$strUnsubscribeInfo     = 'Afmeld en eller flere af vores postlister';
$strContinue            = 'Fortsæt';
$strUnsubscribeSelect   = 'Vælg de postlister du ønsker at afmelde';
$strAllLists            = 'Alle postlister';
$strNoLists             = 'Ingen af dem';
$strNoListsFound        = 'Beklager, du er ikke tilmeldt nogle af vores postlister med denne EMail adresse';
$strResubmit            = 'Gensend EMail';
$strUnsubscribeSubmit   = 'Afmeld de valgte postlister';
$strValuesMissing       = 'De følgende obligatoriske værdier mangler';
$strConfirmInfo 		= 'Tak for bekræftigelse på tilmelding til vores postlister. De postlister du har tilmeldt er vist nedenfor';
$strConfirmTitle 		= 'PHPlist tilmeldings bekræftigelse';

?>