<?php

# language dependent text used in the interface for users (not admin)
# Danish version updated 03. jan 2007

$strCharSet             = 'ISO-8859-1';
$strName                = 'Navn';
$strAddress             = 'Adresse';
$strEmail               = 'Email';
$strTown                = 'By';
$strPostcode            = 'Postnummer';
$strSubscribeInfo       = 'Abonner på et eller flere af vores nyhedslister';
$strRequired            = 'Obligatorisk felt';
$strSubscribeTitle      = 'Abonner på vores nyhedsliste';
$strPleaseSelect        = 'Vælg venligst den nyhedsliste du vil abonnere på';
$strSubmit              = 'Abonner på den valgte nyhedsliste';
$strNotAvailable        = 'Beklager, der er ingen nyhedslister tilrådighed';
$strEnterName           = 'Indtast dit navn';
$strEnterEmail          = 'Indtast din email adresse';
$strInvalidHostInEmail  = 'Beklager, vi kan ikke sende email til dette domæne. Kontroller at du har angivet korrekt email adresse';
$strEnterList           = 'Vælg venligst den nyhedsliste du vil abonnere på';
$strPleaseEnter         = 'Indtast venligst din';
# the thanks message can contain placeholders
#$strThanks              = 'Kære [FIRST NAME], <br/>Tak for dit abonnement på vores nyhedsliste.';
$strThanks              = 'Tak for dit abonnement på vores nyhedsliste.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Din email [email] er blevet tilføjet vores system. Du vil modtage en email med detaljer om dit abonnement';
$strEmailConfirmation   = 'Din email er blevet tilføjet. Du vil om kort tid modtage en mail med et link, som du bedes benytte til at bekræfte dit abonnement.';
$strEmailFailed          = 'Beklager, det mislykkedes at sende en mail med anmodning om at bekræfte dit abonnement, klik "Reload" eller F5 for at forsøge igen. Hvis det stadig mislykkes, kan det skyldes at du står på vores stopliste, hvilket betyder at du ikke kan modtage email fra vores system. hvis det er tilfældet bedes du kontakte administrator.';
$strUnsubscribeTitle    = 'Opsig abonnement på vores nyhedsliste';
$strUnsubscribeDone     = 'Dit abonnement på vores nyhedsliste er blevet opsagt, du vil snarest modtage en mail som bekræfter dette.';
$strBack                = 'Tilbage';
$strUnsubscribeInfo     = 'Opsig abonnement på nyhedsliste';
$strContinue            = 'Forsæt';
$strUnsubscribeSelect   = 'Vælg venligst de nyhedslister du ønsker at opsige abonnement på';
$strAllLists            = 'Alle lister';
$strNoLists             = 'ingen af dem';
$strUnsubscribeRequestForReason = 'Vi er kede af at du ikke længere er interesseret i vores nyhedsliste. For at forbedre vores service, vil vi være glade for en begrundelse på opsigelsen';
$strUnsubscribeFinalInfo = '<br/><b>Bemærk</b>: Denne side er vedrørende <b>opsigelse</b> af abonnement. Hvis du ønsker at ændre din email adresse, eller hvis du ønsker at ændre dit abonnement, bedes du ændre dine  <a href="[PREFERENCESURL]">prefærencer</a>';
$strNoListsFound        = 'Beklager, du abonnerer ikke på nogle af vores nyhedslister med denne email adresse';
$strResubmit            = 'Gen-send email';
$strUnsubscribeSubmit   = 'Opsig abonnement på de valgte nyhedslister';
$strValuesMissing       = 'De følgende obligatoriske felter mangler';
$strConfirmInfo         = 'Tak for din bekræftelse af dit abonnement. Du abonnerer på følgende nyhedslister';
$strConfirmTitle        = '<h3>Bekræftelse af PHPlist medlemsskab</h3>';
$strUserNotFound        = 'Bruger ikke fundet';
$strUserAlreadyInitialised = 'Beklager, dit password er allerede brugt';
$strConfirmFailInfo     = 'Beklager, din anmodning om bekræftelse blev ikke genkendt. Du bedes sikre at den fulde adresse bliver benyttet. Sommetider bliver lange linier brudt op i flere linier';
$strPreferHTMLEmail     = 'Jeg foretrækker at modtage emails i HTML format';
$strPreferTextEmail     = 'Jeg foretrækker at modtage emails i TEKST format';
$strPreferredFormat      = 'Foretrukket format på emails:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Opdater dine prefærencer';
$strPreferencesInfo     = 'Bekræft venligst at nedenstående information er korrekt og klik "Opdater"';
$strUpdatePreferences   = 'Opdater';
$strPreferencesEmailChanged = 'Din email er blevet ændret. Du vil snarest modtage en mail med et link som du bedes benytte til at bekræfte din nye email adresse';
$strYouAreBlacklisted = 'Din email står på vores stopliste, hvilket betyder at du har bedt om ikke at sende dig flere emails. <br/>
For at ændre dette bedes du kontakte administrator, hvor du bedes angive at du ønsker at modtage vores nyhedslister igen.';
$strPreferencesNotificationSent = 'Du vil modtage en email med ændringerne';
$strPreferencesUpdated = 'Tak for dine oplysninger. Vi har opdateret din info.';
$strClickHere          = 'klik her';
$strThisLink           = 'dette link';
$strToUnsubscribe      = 'Hvis du ikke ønsker at modtage flere email, ';
$strToUpdate           = 'For at opdatere din prefærencer eller opsige dit abonnement se venligst';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Ja';
$strNo                 = 'Nej';
$strUnsubscribe        = 'Opsig abonnement';
$strAllMailinglists    = 'Alle nyhedslister';
$strAttachmentIntro     = 'Denne mail indeholder vedhæftede filer som kan ses i en webbrowser:';
$strLocation           = 'Adresse';
$strFrequency           = 'Hvor ofte sender vi din emails';
$strHourly             = 'Hver time';
$strDaily               = 'Dagligt';
$strWeekly             = 'Ugentligt';
$strMonthly             = 'Månedligt';
$strChoosePassword      = 'Vælg et password';
$strConfirmPassword    = 'Bekræft dit password';
$strEnterPassword       = 'Indtast dit password';
$strForgotPassword     = 'Glemt Password';
$strPassword           = 'Password';
$strPassword2           = 'Bekræft Password';
$strPasswordsNoMatch    = 'Passwords er ikke ens';
$strEmailsNoMatch     = 'De indtastede email Adresser er ikke ens';
$strInvalidPassword     = 'Fejl: Ugyldigt email eller password';
$strPasswordSent        = 'Dit password er blevet sendt til dig i en email. Du skulle modtage den inden for få minutter';
$strPasswordRemindSubject = 'Dit password til vores nyhedslister er';
$strPasswordRemindMessage = 'Dit password er ';
$strPasswordRemindInfo = 'For at få sendt dit password indtast din email og klik "'.$strForgotPassword.' knappen';
$strLogin               = 'Login';
$strLoginTitle          = 'Indtast din email og password';
$strLoginInfo           = 'Denne side er passwordbeskyttet. Indtast din email og password';
$strPersonalLocationInfo = '
  <p>Denne side kræver en personligt identifikation, som kan findes i de emails du har modtaget fra os.<br/>
  Hvi sdu er nået hertil ved at klikke på et link, er der muligvis en fejl i linket. Kontroller at du har brugt hele linket, sommetider kan et link være brudt op over flere linier.</p>
  <p>Hvis du ikke kender den rigtige adress kan vi sende dig en mail med et link. Indtast din email og klik "forsæt"';
$strPersonalLocationSent = '<h1>Success! Du vil snarest modtage en mail med dit personlige link</h1>';
$strUserExists   = '<br/>En bruger eksisterer med allerede med den email adresse, vi har et andet password registreret';
$strUserExistsExplanationStart = '<br/>For at modtage dit password, klik';
$strUserExistsExplanationLink = 'her';
$strUserExistsExplanationEnd = ' for at gå til siden hvor du kan anmode om din personlige adresse';
$strForwardTitle = 'Videresend en besked til en ven';
$strForwardSubtitle = 'Videsend besked med emne ';
$strForwardEnterEmail = 'Indtast venligst en gyldig email adresse for videresendelse';
$strForwardSuccessInfo ='Beskeden er blevet videresendt';
$strForwardFailInfo = 'Videresendelse af beskeden mislykkedes';
$strForwardAlreadyDone = 'Denne besked er allerede blevet videresendt til den email adresse';
$strForwardFooter = 'Denne besked er blevet videresendt til dig fra [FORWARDEDBY].
  Du er ikke automatisk blevet tilmeldt denne nyhedsliste.
  For at tilmelde dig til denne nyhedsliste gå til';
$strForward = 'Videresend';
$strFwd = 'Fwd'; # short version of forward for email subject
?>