<?php
# language dependent text used in the interface for users (not admin)
# translation started by Steen Rabøl <srabol@mail.tele.dk>
# translation corrected and continued by Carsten Gehling <carsten@sarum.dk>
# translated for version 2.6.5

$strCharSet             = 'ISO-8859-1';
$strName                = 'Navn';
$strAddress             = 'Adresse';
$strEmail               = 'Email';
$strTown                = 'By';
$strPostcode            = 'Postnr';
$strSubscribeInfo       = 'Tilmeld dig til en eller flere af vores postlister ved at udfylde formularen nedenfor.';
$strRequired            = 'Oligatorisk felt';
$strSubscribeTitle      = 'Tilmeld dig til en af vores postliste';
$strPleaseSelect        = 'Vælg de postlister du ønsker at tilmelde dig';
$strSubmit              = 'Tilmed de valgte postlister';
$strNotAvailable        = 'Beklager, der er ingen postlister tilgængelige';
$strEnterName           = 'Indtast dit navn';
$strEnterEmail          = 'Indtast din e-mail adresse';
$strInvalidHostInEmail  = 'Der kan ikke leveres e-mails til dette domæne. Kontrollér at du har indtastet en korrekt e-mail adresse.';
$strEnterList           = 'Vælg en postliste du ønsker at tilmelde dig';
$strPleaseEnter         = 'Indtast';
# the thanks message can contain placeholders
$strThanks              = 'Kære [FIRST_NAME], <br/>Tak fordi du har tilmeldt dig til en af vore postlister.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Du vil inden for meget kort tid modtage en e-mail med bekrægtigelse på de postlister du har tilmeldt dig';
$strEmailFailed			= 'Der skete en fejl i afsendelsen af en bekræftigelse til dig. Tryk "Opdater" for at prøve igen.';
$strUnsubscribeTitle    = 'Afmeld dig fra en af vores postlister';
$strUnsubscribeDone     = 'Du er blevet afmeldt fra de valgte postlister. Du vil modtage en bekræftigelse inden kort tid.';
$strBack                = 'Tilbage';
$strUnsubscribeInfo     = 'Afmeld en eller flere af vores postlister';
$strContinue            = 'Fortsæt';
$strUnsubscribeSelect   = 'Vælg de postlister du ønsker at afmelde';
$strAllLists            = 'Alle postlister';
$strNoLists             = 'Ingen af dem';
$strNoListsFound        = 'Beklager, du er ikke tilmeldt nogle af vores postlister med denne e-mail adresse';
$strResubmit            = 'Gensend e-mail';
$strUnsubscribeSubmit   = 'Afmeld de valgte postlister';
$strValuesMissing       = 'De følgende obligatoriske værdier mangler';
$strConfirmInfo 		= 'Tak for bekræftigelse på tilmelding til vores postlister. De postlister du har tilmeldt er vist nedenfor';
$strConfirmTitle 		= 'PHPlist tilmeldings bekræftigelse';
$strUserNotFound        = 'Brugeren kunne ikke findes';
$strUserAlreadyInitialised = 'Din adgangskode er allerede sendt.';
$strConfirmFailInfo     = 'Denne bekræftigelse kunne ikke genneføres. Kontroller at du har anvendt den komplette adresse i e-mail\'en. Visse e-mail programmer "knækker" lange linier, og linket fylder derfor to eller flere linier.';
$strPreferHTMLEmail     = 'Jeg ønsker at modtage e-mails i HTML format';
$strPreferTextEmail     = 'Jeg ønsker at modtage e-mails i tekst format';
$strPreferredFormat		= 'Foretrukken e-mail format:';
$strText 								= 'Tekst';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Opdater dine indstillinger';
$strPreferencesInfo     = 'Kontroller at nedenstående information er korrekt, og klik derefter på knappen "Opdater".';
$strUpdatePreferences   = 'Opdater';
$strPreferencesEmailChanged = 'Din e-mail adresse er blevet ændret. Du modtager nu en e-mail med et link. Klik på dette link, for at bekræfte din nye e-mail adresse.';
$strPreferencesNotificationSent = 'Du modtager nu en e-mail med ændringerne.';
$strPreferencesUpdated = 'Tak for dine ændringer, vi har opdateret dine indstillinger.';
$strClickHere          = 'Klik her';
$strThisLink           = 'dette link';
$strToUnsubscribe      = 'For at opsige abonnementet på denne liste klik';
$strToUpdate           = 'For at ændre dine personlige indstillinger klik';
$strSendHTML           = 'Send HTML e-mail';
$strYes                = 'Ja';
$strNo                 = 'Nej';
$strUnsubscribe        = 'Opsig abonnement';
$strAttachmentIntro	   = 'Denne e-mail indeholder vedhæftede filer, der kan ses i en web browser:';
$strLocation			 = 'Lokalitet';
$strFrequency			 = 'Hvor tit sender vi e-mails til dig';
$strHourly				 = 'En gang i timen';
$strDaily				 = 'Dagligt';
$strWeekly				 = 'Ugenligt';
$strMonthly				 = 'Månedligt';
$strChoosePassword 		 = 'Vælg en adgangskode';
$strConfirmPassword 	 = 'Bekræft din adgangskode';
$strEnterPassword		 = 'Indtast din adgangskode';
$strForgotPassword		 = 'Glemt adgangskode';
$strPassword			 = 'Adgangskode';
$strPassword2			= 'Bekræft adgangskode';
$strPasswordsNoMatch 	 = 'De to adgangskoder er ikke ens';
$strInvalidPassword		 = 'Forkert e-mail eller adgangskode';
$strPasswordSent 		   = 'Vi har sendt en e-mail med din adgangskode, som du modtager indenfor få minutter.';
$strPasswordRemindSubject = 'Din adgangskode for vores lister';
$strPasswordRemindMessage = 'Din adgangskode er ';
$strPasswordRemindInfo = 'For at få din adgangskode tilsendt, skal du skrive din e-mail adresse og derefter trykke på knappen "'.$strForgotPassword.'".';
$strLogin							 = 'Login';
$strLoginTitle 				 = 'Indtast din e-mail adresse og adgangskode';
$strLoginInfo					 = 'Denne side kræver en adgangskode. Indtast din e-mail adresse og adgangskode';
$strPersonalLocationInfo = '
<p>
	Denne side kræver en personlig identifikation, som du finder i hver eneste e-mail, vi sender.
	<br/>
	Hvis du er nået hertil ved at klikke på et link i e-mailen, er der muligvis en fejl i det link,
	som du bruger. Visse e-mail programmer "knækker" lange linier, og linket fylder derfor to eller
	flere linier.
</p>
<p>
	Hvis du ikke kender den rigtige adresse, kan du anmode om at få tilsendt en e-mail, som
	indeholder den rigtige adresse.
	Indtast din e-mail adresse i feltet og klik "Fortsæt".
';
$strPersonalLocationSent = '<h1>Du modtager inden for få minutter en e-mail med din personlige adresse.</h1>';
?>
