
<?

# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat 
# update by Mike Rijken, 18/11/2002
# review by Rudi Van Overloop, ruda@skynet.be 27/2/2004

$strCharSet             = 'ISO-8859-1';
$strName                = 'Naam';
$strAddress             = 'Adres';
$strEmail               = 'Email';
$strTown                = 'Plaatsnaam';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Meld u aan voor een van onze nieuwsbrieven door onderstaand formulier in te vullen';
$strRequired            = 'verplicht veld';
$strSubscribeTitle      = 'Meld u aan voor een nieuwsbrief';
$strPleaseSelect        = 'Selecteer de nieuwsbrief waarvoor u zich wilt aanmelden';
$strSubmit              = 'Aanmelden bij de geselecteerde nieuwsbrieven';
$strNotAvailable        = 'Er zijn momenteel geen nieuwsbrieven beschikbaar';
$strPleaseEnter         = 'Vul het volgende in: ';
$strEnterName           = 'Vul uw naam in';
$strEnterEmail          = 'Vul uw e-mailadres in';
$strEnterList           = 'Selecteer een nieuwsbrief om aan te melden';
$strThanks              = 'Dank u voor het aanmelden op onze nieuwsbrief.';
$strEmailConfirmation   = 'U ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging van uw aanmelding.';
$strUnsubscribeTitle    = 'Afmelden op onze nieuwsbrief';
$strUnsubscribeDone     = 'U bent afgemeld op de geselecteerde nieuwsbrief en u ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Afmelden op een van onze nieuwsbrieven';
$strContinue            = 'Volgende';
$strUnsubscribeSelect   = 'Selecteer de nieuwsbrief waarop u zich wilt afmelden.';
$strAllLists            = 'Alle nieuwsbrieven';
$strNoLists             = 'Geen enkele nieuwsbrief';
$strNoListsFound        = 'Sorry, u heeft met dit e-mailadres geen abonnement op een van onze nieuwsbrieven.';
$strResubmit            = 'Nogmaals e-mailadres';
$strUnsubscribeSubmit   = 'Afmelden op de geselecteerde nieuwsbrieven';
$strValuesMissing       = 'De volgende verplichte velden zijn niet ingevuld';
$strConfirmInfo         = 'Dank u voor het bevestigen van uw aanmelding. De nieuwsbrief waarop u bent geabonneerd wordt hieronder weergegeven';
$strConfirmTitle        = 'Bevestiging';
$strUserNotFound        = 'Gebruiker niet gevonden';
$strPreferHTMLEmail     = 'Ik geef de voorkeur aan het ontvangen van emails in HTML formaat.';
$strSendHTML            = 'Verstuur HTML email';
$strConfirmFailInfo     = 'Sorry, er is een fout opgetreden tijdens de bevestiging van uw aanmelding. De foutmelding staat hieronder.';
$strPreferencesTitle    = 'Vernieuw uw instellingen';
$strPreferencesInfo     = 'Als de informatie hieronder correct is kunt u gewoon op de "wijzig" knop klikken om te bewaren';
$strUpdatePreferences   = 'wijzig';
$strPreferencesEmailChanged = 'Uw email is gewijzigd. Klik op de link in de email die u zo meteen ontvangt om de wijziging te bevestigen.';
$strPreferencesNotificationSent = 'u ontvangt een email met de wijzigingen';
$strPreferencesUpdated = 'Wij hebben uw instellingen vernieuwd';
$strClickHere          = 'Klik hier';
$strThisLink           = 'deze link';
$strToUnsubscribe      = 'Om u van deze nieuwsbrief af te melden bezoek';
$strToUpdate           = 'Om uw voorkeuren te wijzigen bezoek';
$strSendHTML           = 'Verstuur HTML email';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Afmelden';
$strAllMailinglists    = 'Alle nieuwsbrieven';
$strChoosePassword 	   = 'Kies een paswoord aub';
$strConfirmPassword    = 'Bevestig uw paswoord aub';
$strEnterPassword	   = 'Vul je paswoord in aub';
$strForgotPassword	   = 'Paswoord vergeten';
$strPassword		   = 'Paswoord';
$strPassword2		   = 'Bevestig paswoord';
$strPasswordsNoMatch   = 'Paswoorden komen niet overeen';
$strInvalidPassword	   = 'FOUT: ongeldig e-mail of paswoord';
$strPasswordSent 	   = 'Uw paswoord is naar uw e-mail verzonden. U zal het over enkele ogenblikken ontvangen';
$strPasswordRemindSubject = 'Uw paswoord voor onze nieuwsbrieven';
$strPasswordRemindMessage = 'Uw paswoord is ';
$strPasswordRemindInfo    = 'Om het paswoord via e-mail te ontvangen, vul je e-mail adres in en klik op het "'.$strForgotPassword.'" knopje.';
$strLogin				  = 'Inloggen';
$strLoginTitle 			  = 'Vul Uw e-mail adres en paswoord in aub';
$strLoginInfo			  = 'Deze pagina vereist een paswoord. Vul Uw e-mail adres en paswoord in aub';
$strPersonalLocationInfo = '
	<p>Deze pagina vereist een persoonlijke identificatie dewelke u kan terugvinden in elke e-mail dat we u sturen.<br/>
  Kijk nog eens goed de juiste URL in je browser na wanneer u een foutmelding ontvangt.
  De URL kan soms over 2 tekstlijnen verdeeld zijn.</p>
  <p>Wanneer U de URL niet kan terugvinden, kan je deze eenvoudig per e-mail aanvragen.
  Vul je e-mail adres in aub en klik op "Continue"';
$strPersonalLocationSent = '<h1>Gefeliciteerd! U zal kortelings een bericht ontvangen met een overzicht van Uw persoonlijke instellingen.</h1>';
?>
