
<?

# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat 
# update by Mike Rijken, 18/11/2002

$strName                = 'Naam';
$strAddress             = 'Adres';
$strEmail               = 'Email';
$strTown                = 'Plaatsnaam';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Meld u aan op een van onze nieuwsbrieven door onderstaand formulier in te vullen';
$strRequired            = 'verplicht veld';
$strSubscribeTitle      = 'Meld u aan op onze nieuwsbrieven';
$strPleaseSelect        = 'Selecteer de nieuwsbrief waarvoor u zich wilt aanmelden';
$strSubmit              = 'Aanmelden bij de geselecteerde nieuwsbrieven';
$strNotAvailable        = 'Er zijn momenteel geen nieuwsbrieven beschikbaar';
$strPleaseEnter         = 'Vul het volgende in: ';
$strEnterName           = 'Vul uw naam in';
$strEnterEmail          = 'Vul uw e-mailadres in';
$strEnterList           = 'Selecteer een nieuwsbrief om aan te melden';
$strThanks              = 'Dank u voor het aanmelden op onze nieuwsbrief.';
$strEmailConfirmation   = 'U ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging van uw aanmelding.';
$strUnsubscribeTitle    = 'Afmelden op onze nieuwsbrief';
$strUnsubscribeDone     = 'U bent afgemeld op de geselecteerde nieuwsbrief en u ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Afmelden op een van onze nieuwsbrieven';
$strContinue            = 'Volgende';
$strUnsubscribeSelect   = 'Selecteer de nieuwsbrief waarop u zich wilt afmelden.';
$strAllLists            = 'Alle nieuwsbrieven';
$strNoLists             = 'Geen enkele nieuwsbrief';
$strNoListsFound        = 'Sorry, u heeft met dit e-mailadres geen abonnement op een van onze nieuwsbrieven.';
$strResubmit            = 'Nogmaals e-mailadres';
$strUnsubscribeSubmit   = 'Afmelden op de geselecteerde nieuwsbrieven';
$strValuesMissing       = 'De volgende verplichte velden zijn niet ingevuld';
$strConfirmInfo         = 'Dank u voor het bevestigen van uw aanmelding. De nieuwsbrief waarop u bent geabonneerd wordt hieronder weergegeven';
$strConfirmTitle        = 'Bevestiging';
$strUserNotFound        = 'Gebruiker niet gevonden';
$strPreferHTMLEmail     = 'Ik geef de voorkeur aan het ontvangen van emails in HTML formaat.';
$strSendHTML           = 'Verstuur HTML email';
$strConfirmFailInfo     = 'Sorry, er is een fout opgetreden tijdens de bevestiging van uw aanmelding. De foutmelding staat hieronder.';
$strPreferencesTitle    = 'Vernieuw uw instellingen';
$strPreferencesInfo     = 'Als de informatie hieronder correct is kunt u op de "wijzig" knop klikken';
$strUpdatePreferences   = 'wijzig';
$strPreferencesEmailChanged = 'Uw email is gewijzigd. Klik op de link in de email die u zo meteen ontvangt om de wijziging te bevestigen.';
$strPreferencesNotificationSent = 'u ontvangt een email met de wijzigingen';
$strPreferencesUpdated = 'Wij hebben uw instellingen vernieuwd';
$strClickHere          = 'Klik hier';
$strThisLink           = 'deze link';
$strToUnsubscribe      = 'Om u van deze nieuwsbrief af te melden bezoek';
$strToUpdate           = 'Om uw voorkeuren te wijzigen bezoek';
$strSendHTML           = 'Verstuur HTML email';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Afmelden';

?>
