<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Name';
$strAddress             = 'Address';
$strEmail               = 'Email';
$strTown                = 'Town';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Subscribe to one or more of our newsletters using the form below';
$strRequired            = 'required field';
$strSubscribeTitle      = 'Subscribe to our Newsletters';
$strPleaseSelect        = 'Please select the newsletters you want to sign up to';
$strSubmit              = 'Subscribe to the Selected Newsletters';
$strNotAvailable        = 'Sorry there are currently no newsletters available';
$strEnterName           = 'Please enter your name';
$strEnterEmail          = 'Please enter your email address';
$strInvalidHostInEmail  = 'Sorry, email to that domain is undeliverable, please check that you typed the correct email address';
$strEnterList           = 'Please select a newsletter to subscribe to';
$strPleaseEnter         = 'Please enter your';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Thank you for subscribing to our newsletters.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Your email has been added to our system. You will be e-mailed shortly with a request to confirm your membership. Please make sure to click the link in that message to confirm your subscription.';
$strEmailFailed          = 'Sorry, sending the email to request your confirmation failed, please click "Reload" to try again. If it still does not work, it may be because you are listed on our "Black List", which means that you cannot receive emails from our newsletter system. In that case, please contact the administrator.';
$strUnsubscribeTitle    = 'Unsubscribe from our Newsletters';
$strUnsubscribeDone     = 'You have been unsubscribed from our newsletters and you will receive confirmation by email soon.';
$strBack                = 'Back';
$strUnsubscribeInfo     = 'Unsubscribe from our newsletters';
$strContinue            = 'Continue';
$strUnsubscribeSelect   = 'Please select the newsletters you want to unsubscribe from';
$strAllLists            = 'All Lists';
$strNoLists             = 'None of them';
$strUnsubscribeRequestForReason = 'We are sorry to find you are not any longer interested in our newsletter. To help us improve our services, we would be grateful if you could tell us why:';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page is to stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strNoListsFound        = 'Sorry, you are not subscribed to any of our newsletters with this email';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = 'Unsubscribe from the Selected Newsletters';
$strValuesMissing       = 'The following required values are missing';
//$strConfirmInfo         = 'Thank you for confirming your subscription to our newsletters. The newsletters you are subscribed to are listed below';
$strConfirmInfo		='<h2>Welcome to MyICA</h2><p>Thank you for confirming your subscription to our newsletters.</p><p>The newsletters you are subscribed to are listed below.</p><p>You can edit your <a href="http://www.ica.org.uk/?lid=11835">profile</a>, view your <a href="http://www.ica.org.uk/?lid=11835">subscriptions</a>, and change your <a href="http://www.ica.org.uk/?lid=11994">password</a>.</p>';

$strConfirmTitle        = 'ICA membership confirmation page';



$strUserNotFound        = 'User not found';
$strUserAlreadyInitialised = 'Sorry, your password has already been set';
$strConfirmFailInfo     = 'Sorry, your request for confirmation was not recognised. Please make sure to use the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
$strPreferHTMLEmail     = 'I prefer to receive emails in HTML format';
$strPreferTextEmail     = 'I prefer to receive emails in Text format';
$strPreferredFormat      = 'Preferred format for emails:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Update your preferences';
$strPreferencesInfo     = 'Please confirm that the information below is correct and click the "Update" button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Your email has changed. Please visit the link in the email you will receive to confirm your new email address';
$strYouAreBlacklisted = 'Your email is listed in our "Black List", which means that you have requested us never to send you any more newsletters. <br/>
In order to receive emails again, manual intervention is required by our administrator. Please contact us stating explicitly that you want to receive newsletters again, and we will
take you off our black list. ';
$strPreferencesNotificationSent = 'You will receive an email with the changes';
$strPreferencesUpdated = 'Thank you for your submission. We have updated your information.';
$strClickHere          = 'Click Here';
$strThisLink           = 'this link';
$strToUnsubscribe      = 'If you do not want to receive any more newsletters, ';
$strToUpdate           = 'To update your preferences and to unsubscribe visit';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Yes';
$strNo                 = 'No';
$strUnsubscribe        = 'Unsubscribe';
$strAllMailinglists    = 'All newsletters';
$strAttachmentIntro     = 'This message contains attachments that can be viewed with a webbrowser:';
$strLocation           = 'Location';
$strFrequency           = 'How often do we send you messages';
$strHourly             = 'Hourly';
$strDaily               = 'Daily';
$strWeekly             = 'Weekly';
$strMonthly             = 'Monthly';
$strChoosePassword      = 'Please choose a password';
$strConfirmPassword    = 'Confirm your password';
$strEnterPassword       = 'Please enter your password';
$strForgotPassword     = 'Forgot Password';
$strPassword           = 'Password';
$strPassword2           = 'Confirm Password';
$strPasswordsNoMatch    = 'Passwords are not the same';
$strEmailsNoMatch     = 'Email Addresses you entered do not match';
$strInvalidPassword     = 'Error: invalid email or password';
$strPasswordSent        = 'Your password has been sent to your by email. You should receive it in the next few minutes';
$strPasswordRemindSubject = 'Your password for our newsletters';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = 'To receive your password by email, please enter your email and click the "'.$strForgotPassword.'" button.';
$strLogin               = 'Login';
$strLoginTitle          = 'Please enter your email address and password';
$strLoginInfo           = 'This page requires a password. Please enter your email address and password';
$strPersonalLocationInfo = '
  <p>This page requires a personal identification that can be found on each email that we send you.<br/>
  If you have clicked this location, and you get this error, please make sure to paste the entire line into the
  location box of your browser. Sometimes the location is wrapped over several lines.</p>
  <p>If you do not know the location, you can request an email that will tell you what it is.
  Please enter your email in the box and click "Continue"
';
$strPersonalLocationSent = '<h1>Success! You should receive a message with your personal location shortly</h1>';
$strUserExists   = '<br/>A user with that email already exists, and our records contain a different password';
$strUserExistsExplanationStart = '<br/>In order to obtain your password, click ';
$strUserExistsExplanationLink = 'here';
$strUserExistsExplanationEnd = ' to go to the page where you can request your personal location';
$strForwardTitle = 'Forward a Message to Someone';
$strForwardSubtitle = 'Forwarding the message with subject ';
$strForwardEnterEmail = 'Please enter a valid email address to forward to';
$strForwardSuccessInfo ='The message has been forwarded';
$strForwardFailInfo = 'Forwarding the message failed';
$strForwardAlreadyDone = 'This message has already been successfully forwarded to that email address';
$strForwardFooter = 'This message has been forwarded to you by [FORWARDEDBY].
  You have not been automatically subscribed to this newsletter.
  To subscribe to this newsletter go to';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
//$strDefaultSetting = 'Default setting. To change it write it here, to use this leave it like this.';
$strValueNotFound = 'Value not found. Check your required vars and their values.';
$strPhplistDbCreation = 'Now let\'s try to create the db. Fill in the form bellow to do it.';
$strPhplistDbWrongOk = '<p class="allwrong">Default database and/or user/pass are wrong, that\'s ok, let\'s continue.</p>';
$strPhplistDefaultDbOk = '<p class="allok">Hmm, the default settings for database connection worked ok. You dont want to use phplist with these values, is not safe, you better change them and create a user for the database before continue.</p>';
$strDbname = 'Database name : ';
$strDbhost = 'Database host, usually \'localhost\' : ';
$strDbuser = 'Database user, previously created : ';
$strDbpass = 'Database pass of your user : ';
$strDbCreatedOk = 'Database created succesfully. The next step will create a config file for your system here.';
$strDbCreatedKo = 'Could not create database, check the permissions of your user. Or ask your host provider to create one for you and then go to the next step.<p>Fill in the form again, installer will not continue if there isn\'t a databases.</p>';
$myConfigFileOpen = '<b>Your next step is to chmod your /lists/config/config.php file to 644. Right now is 666, and this is not safe, your installation can be hacked if you don\'t do this</b>';
$popAccountOk = '<strong>Your bounces POP3 account has responded ok.</strong>';
$popAccountKo = 'Warning: Your bounces email account details are wrong, I couldn\'t create POP3 connection to ';
$strFinal = '<p>These are the values that we are going to write to your config, is everything ok? If not go back and change it.</p>';
$dbAlreadyCreated = 'Great, the database is working ok, go to the next step.';
$noConfigAndChmod = 'Could not open config file to write, and could not chmod to be writable. The whole thing will fail... Have fun.';
$creatingConfig = 'Creating config file...';
$cantWriteToConfig = 'I couldnt right to the config file, HGRR!! Check the permissions again';
$configCreatedOk = 'Config file created OK.';
$configDoesntExist = 'Config file doesnt exists, something went wrong...';
//$noConfigFileThere = 'Your config file doesnot exists, phplist will try to create one, but it might fail. Please check the permissions on the lists/config directory and start the installation';
//$yesConfigFileNotWritable = 'Your config file exists, but is not writable. Change permissions to writable, ie 666 or 777 and continue with the installation';
//$goodConfigFile = 'Your config file is ready for writing (mmm, maybe we have to check if it\'s empty...).';
$strConfigIsNotAndDirNotWri = 'Warning: Your config file doesnt exists, and phplist cannot write into the lists/config directory. Please either create a config.php file with write permissions, or change permissions to the lists/config directory to be executable (ie 755) before continue.';
$strConfigIsNotWritable = 'Warning: Your config file is not writable, please change the permissions of the lists/config/config.php file to be writable (ie 666, 646, 777, etc).';
$strConfigPerms = 'Warning: Your config permissions are now';
$strChangeChmod = ', phplist could not change it, please change permissions to 0644 to your lists/config/config.php file. Right now your phplist config is not safe, so do this before continue with the installation of the system.';
$strIntroInstaller = '<p>Phplist installer will help you to create your database and config file for the system in several steps. Please keep in mind that if permissions are not well set up phplist won\'t be able to create either your db or your config file. The best thing to do first is to check if you have the right permissions so the installer will work well.</p>
<p>You can always make the manual install following the instructions <a href="http://docs.phplist.com/PhplistInstallation">here</a>.</p>
<p>In several steps, as said, installer will check for all the configuration needed to start using the system. Some advances features are not availables for edit for now, if you still want to use them you will have to edit those manually after the creation of the config file.</p>

<p>For more help undertanding phplist install you can take a look at <a href="http://docs.phplist.com/">phplist docs</a>, <a href="http://mantis.phplist.com/">mantis</a> for report a bug or ask for a future feature and the <a href="http://forums.phplist.com/">forums</a> for tips, answers and extra help.</p>';
$strStartInstall = 'Let\'s start the installation in the next page, click <a href="step0-install.php">here to start the install of your phplist version.</a> Good luck! ;)';
$strInstallerTitle = 'installer';
$strConfigHasContent = 'Warning: Your config file already has content, which means that it was already initialised. If you want to use the installer please clean the file.';
$strTmpNotWritable = 'Warning: Your actual tmp directory is not writable, please right a complete path in the inputs below.';
$strStillNoConnection = 'Warning: Your database details are still wrong, I couldn\'t connect to it. Please, come back and define the details again. Be sure to have Caps Lock disable in your keyboard, and check your spelling.';
$strTmpIsOk = '<p><strong>Your tmp/ folder works ok right now, change them below only if you are sure.</strong></p>';
$strNoDbCannotContinue = 'Fatal error: Still no connection to the database, installer will not continue. Please check it or create one to continue.';
$strStartAgain = 'Click below to start the installer again, your database details were wrong.';
$strReload = 'Please do what is described above and refresh to start the install.';
$strGoToInitialiseDb = 'Click in the link and go to your installation to initialise the db ';
$addFeature = 'Or maybe you want to add a new feature to the config file? If yes click this';
$strChangedForThis = 'I have changed it for this => ';
$strErraticValue = ' will cause a syntax error. The erratic value is = ';

?>