<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Name';
$strAddress             = 'Address';
$strEmail               = 'Email';
$strTown                = 'Town';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Subscribe to one or more of our mailing lists using the form below';
$strRequired            = 'required field';
$strSubscribeTitle      = 'Subscribe to our Mailing lists';
$strPleaseSelect        = 'Please select the lists you want to sign up to';
$strSubmit              = 'Subscribe to the Selected Mailinglists';
$strNotAvailable        = 'Sorry there are currently no lists available';
$strEnterName           = 'Please enter your name';
$strEnterEmail          = 'Please enter your email address';
$strInvalidHostInEmail  = 'Sorry, email to that domain is undeliverable, please check that you typed the correct email address';
$strEnterList           = 'Please select a list to subscribe to';
$strPleaseEnter         = 'Please enter your';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Thank you for subscribing to our lists.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Your email has been added to our system. You will be e-mailed shortly with a request to confirm your membership. Please make sure to click the link in that message to confirm your subscription.';
$strEmailFailed					= 'Sorry, sending the email to request your confirmation failed, please click "Reload" to try again.';
$strUnsubscribeTitle    = 'Unsubscribe from our Mailinglists';
$strUnsubscribeDone     = 'You have been unsubscribed from the mailinglists you selected and you will receive confirmation by email soon.';
$strBack                = 'Back';
$strUnsubscribeInfo     = 'Unsubscribe from one or more of our mailinglists';
$strContinue            = 'Continue';
$strUnsubscribeSelect   = 'Please select the lists you want to unsubscribe from';
$strAllLists            = 'All Lists';
$strNoLists             = 'None of them';
$strNoListsFound        = 'Sorry, you are not subscribed to any of our mailinglists with this email';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = 'Unsubscribe from the Selected Mailinglists';
$strValuesMissing       = 'The following required values are missing';
$strConfirmInfo         = 'Thank you for confirming your subscription to our lists. The lists you are subscribed to are listed below';
$strConfirmTitle        = 'PHPlist membership confirmation page';
$strUserNotFound        = 'User not found';
$strUserAlreadyInitialised = 'Sorry, your password has already been set';
$strConfirmFailInfo     = 'Sorry, your request for confirmation was not recognised. Please make sure to use the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
$strPreferHTMLEmail     = 'I prefer to receive emails in HTML format';
$strPreferTextEmail     = 'I prefer to receive emails in Text format';
$strPreferredFormat			= 'Preferred format for emails:';
$strText 								= 'Text';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Update your preferences';
$strPreferencesInfo     = 'Please confirm that the information below is correct and click the "Update" button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Your email has changed. Please visit the link in the email you will receive to confirm your new email address';
$strPreferencesNotificationSent = 'You will receive an email with the changes';
$strPreferencesUpdated = 'Thank you for your submission. We have updated your information.';
$strClickHere          = 'Click Here';
$strThisLink           = 'this link';
$strToUnsubscribe      = 'To unsubscribe from this list visit';
$strToUpdate           = 'To update your preferences visit';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Yes';
$strNo                 = 'No';
$strUnsubscribe        = 'Unsubscribe';
$strAllMailinglists    = 'All mailinglists';
$strAttachmentIntro		 = 'This message contains attachments that can be viewed with a webbrowser:';
$strLocation					 = 'Location';
$strFrequency					 = 'How often do we send you messages';
$strHourly						 = 'Hourly';
$strDaily							 = 'Daily';
$strWeekly						 = 'Weekly';
$strMonthly						 = 'Monthly';
$strChoosePassword 		 = 'Please choose a password';
$strConfirmPassword 	 = 'Confirm your password';
$strEnterPassword			 = 'Please enter your password';
$strForgotPassword		 = 'Forgot Password';
$strPassword					 = 'Password';
$strPassword2					 = 'Confirm Password';
$strPasswordsNoMatch 	 = 'Passwords are not the same';
$strInvalidPassword		 = 'Error: invalid email or password';
$strPasswordSent 		   = 'Your password has been sent to your by email. You should receive it in the next few minutes';
$strPasswordRemindSubject = 'Your password for our lists';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = 'To receive your password by email, please enter your email and click the "'.$strForgotPassword.'" button.';
$strLogin							 = 'Login';
$strLoginTitle 				 = 'Please enter your email address and password';
$strLoginInfo					 = 'This page requires a password. Please enter your email address and password';
$strPersonalLocationInfo = '
	<p>This page requires a personal identification that can be found on each email that we send you.<br/>
  If you have clicked this location, and you get this error, please make sure to paste the entire line into the 
  location box of your browser. Sometimes the location is wrapped over several lines.</p>
  <p>If you do not know the location, you can request an email that will tell you what it is.
  Please enter your email in the box and click "Continue"
';
$strPersonalLocationSent = '<h1>Success! You should receive a message with your personal location shortly</h1>';
$strUserExists   = '<br/>A user with that email already exists, and our records contain a different password';
$strUserExistsExplanationStart = '<br/>In order to obtain your password, click ';
$strUserExistsExplanationLink = 'here';
$strUserExistsExplanationEnd = ' to go to the page where you can request your personal location';

?>
