<?php

# language dependent text used in the interface for users (not admin)

$strName                = 'Name';
$strAddress             = 'Addresse';
$strEmail               = 'E-Mail';
$strTown                = 'Wohnort';
$strPostcode            = 'Postfach';
$strSubscribeInfo       = 'Zum Anmelden bei einer oder mehreren unserer Mailinglisten ben&uuml;tzen Sie das nachfolgende Formular!';
$strRequired            = 'Ben&ouml;tigte Felder:';
$strSubscribeTitle      = 'Anmelden bei der Mailingliste';
$strPleaseSelect        = 'Bitte w&auml;hlen Sie eine oder mehrere Listen, bei denen Sie sich anmelden wollen';
$strSubmit              = 'Anmelden bei den ausgew&auml;hlten Mailinglisten';
$strNotAvailable        = 'Derzeit sind keine Listen verf&uuml;gbar';
$strEnterName           = 'Bitte geben Sie ihren Namen ein';
$strEnterEmail          = 'Bitte geben Sie ihre E-Mail Adresse ein';
$strEnterList           = 'Bitte w&auml;hlen Sie ein Liste aus, bei der Sie sich anmelden wollen';
$strPleaseEnter			= 'Bitte geben Sie ein';
$strThanks              = 'Danke f&uuml;r die Anmeldung bei unseren Listen.';
$strEmailConfirmation   = 'Sie erhalten in k&uuml;rze eine E-Mail mit der Best&auml;tigung der Listen bei denen Sie sich angemeldet haben.';
$strUnsubscribeTitle    = 'Abmelden von unseren Mailinglisten';
$strUnsubscribeDone     = 'Sie wurden von den Mailinglisten die Sie ausgew&auml;hlt haben abgemeldet, eine Best&auml;tigung erhalten Sie in k&uuml;rze per E-Mail.';
$strBack                = 'Zur&uuml;ck';
$strUnsubscribeInfo     = 'Abmelden von einer oder mehreren unserer Mailinglisten';
$strContinue            = 'Weiter';
$strUnsubscribeSelect   = 'Bitte w&auml;hlen Sie die Listen von denen Sie sich abmelden wollen';
$strAllLists            = 'Alle Listen';
$strNoLists             = 'Keine von diesen';
$strNoListsFound        = 'Sie wurden mit dieser E-Mail bei keiner unserer Mailinglisten angemeldet';
$strResubmit            = 'Erneut versuchen';
$strUnsubscribeSubmit   = 'Abmelden von den gew&auml;hlten Mailinglisten';
$strValuesMissing       = 'Die folgenden ben&ouml;tigten Felder fehlen';
$strConfirmInfo 		= 'Danke f&uuml;r die Best&auml;tigung. Sie wurden auf folgenden Listen eingeschrieben:';
$strConfirmTitle 		= 'Best&auml;tigungsseite';
$strUserNotFound		= 'User nicht gefunden';
$strConfirmFailInfo		= 'Es trat ein Fehler auf. Details:';


?>