<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nome';
$strAddress             = 'Indirizzo';
$strEmail               = 'Email';
$strTown                = 'Comune';
$strPostcode            = 'CAP';
$strSubscribeInfo       = 'Iscriviti ad una o più mailinglists utilizzando il modulo seguente';
$strRequired            = 'campo obbligatorio';
$strSubscribeTitle      = 'Iscriviti alla nostra Mailinglists';
$strPleaseSelect        = 'Per favore, seleziona la lista a cui ti vuoi segnare';
$strSubmit              = 'Iscriviti alle Mailinglists selezionate';
$strNotAvailable        = 'Spiacenti, ma non ci sono liste disponibili';
$strEnterName           = 'Per favore, inserisci il tuo nome';
$strEnterEmail          = 'Per favore, inserisci il tuo indirizzo email';
$strInvalidHostInEmail  = 'Spiacenti, ma il tuo indirizzo email non è raggiungibile, per favore controlla che questo sia stato scritto correttamente';
$strEnterList           = 'Per favore, seleziona una lista cui iscriverti';
$strPleaseEnter         = 'Per favore, inserisci il tuo';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Grazie per esserti iscritto alle nostre liste.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Il tuo indirizzo email è stato aggiunto nel nostro sistema. A breve, riceverai una email con la richiesta di confermare la tua iscrizione. Per favore, clicca sul link contenuto nel messaggio per confermarla.';
$strEmailFailed = "Spiacenti, l'invio del messaggio con la richiesta di iscrizione è fallito, per favore, clicca su 'Aggiorna' per tentare di nuovo.";
$strUnsubscribeTitle    = 'Cancellati dalle nostre Mailinglists';
$strUnsubscribeDone     = 'Sei stato cancellato dalle mailinglists che hai selezionato, riceverai a breve una email di conferma.';
$strBack                = 'Indietro';
$strUnsubscribeInfo     = 'Cancellati da una o più mailinglists';
$strContinue            = 'Procedi';
$strUnsubscribeSelect   = 'Per favore, seleziona le liste da cui ti vuoi cancellare';
$strAllLists            = 'Tutte le liste';
$strNoLists             = 'Nessuna';
$strNoListsFound        = 'Spiacenti, ma non sei iscritto a nessuna mailinglists with this email';
$strResubmit            = "Reinvia l'Email";
$strUnsubscribeSubmit   = 'Cancellati dalle Mailinglists selezionate';
$strValuesMissing       = 'I seguenti campi obbligatori sono mancanti';
$strConfirmInfo         = "Grazie per aver confermato l'iscrizione alle nostre liste. Le liste cui sei iscritto sono elencate di seguito";
$strConfirmTitle        = 'PHPlist pagina di conferma delle iscrizioni';
$strUserNotFound        = 'Utente non trovato';
$strUserAlreadyInitialised = 'Spiacenti, ma la tua password è stata già settata';
$strConfirmFailInfo     = "Spiacenti, ma la richiesta di conferma dell'iscrizione non è stata riconosciuta. Per favore, controlla che l'intero indirizzo web indicato nel messaggio sia stato scritto nel browser. A volte può succedere che questo sia spezzato su più righe.";
$strPreferHTMLEmail     = 'Preferisco ricevere le emails in formato HTML';
$strPreferTextEmail     = 'Preferisco ricevere le emails in formato Testo';
$strPreferredFormat	= 'Formato preferito per le emails:';
$strText 		= 'Testo';
$strHTML		= 'HTML';
$strPreferencesTitle    = 'Aggiorna le tue preferenze';
$strPreferencesInfo     = "Per favore, controlla che il seguente dato sia corretto e clicca sul bottone 'Aggiorna'";
$strUpdatePreferences   = 'Aggiorna';
$strPreferencesEmailChanged = 'Il tuo indirizzo email è stato cambiato. Per favore, clicca sul link contenuto nel messaggio che riceverai a breve per confermare il nuovo indirizzo';
$strPreferencesNotificationSent = 'Riceverai un messaggio email con le modifiche';
$strPreferencesUpdated	= 'Grazie per i dati che ci hai fornito. Abbiamo aggiornato le informazioni della tua scheda.';
$strClickHere		= 'Clicca Qui';
$strThisLink		= 'questo link';
$strToUnsubscribe	= 'Per cancellarti da questa lista clicca su questo link';
$strToUpdate		= 'Per aggiornare le tue preferenze clicca su questo link';
$strSendHTML		= 'Invia una email HTML';
$strYes			= 'Sì';
$strNo			= 'No';
$strUnsubscribe		= 'Cancellare';
$strAttachmentIntro	= 'Questo messaggio contiene allegati che possono essere visti con un browser:';
$strLocation		= 'Luogo';
$strFrequency		= 'Frequenza dei nostri messaggi';
$strHourly		= 'Ogni ora';
$strDaily		= 'Giornaliera';
$strWeekly		= 'Settimanale';
$strMonthly		= 'Mensile';
$strChoosePassword 	= 'Per favore, scegli una password';
$strConfirmPassword 	= 'Conferma la password';
$strEnterPassword	= 'Per favore, inserisci la tua password';
$strForgotPassword	= 'Password dimenticata';
$strPassword		= 'Password';
$strPassword2		= 'Conferma Password';
$strPasswordsNoMatch 	= 'Le Passwords non corrispondono';
$strInvalidPassword	= 'Errore: email o password non validi';
$strPasswordSent 	= 'La tua password è stata inviata al tuo indirizzo email. Dovresti riceverla a breve';
$strPasswordRemindSubject = 'Invio password per mailing-lists';
$strPasswordRemindMessage = 'La tua password è';
$strPasswordRemindInfo	= 'Per ricevere la tua password tramite email, per favore, inserisci il tuo indirizzo email e clicca sul bottone "'.$strForgotPassword.'".';
$strLogin		= 'Login';
$strLoginTitle 		= 'Per favore, inserisci il tuo indirizzo email e la password';
$strLoginInfo		= 'Questa pagina richiede una password. ' . $strLoginTitle;
$strPersonalLocationInfo = "
 <p>Questa pagina richiede un identificativo personale che può essere
 trovato in ogni messaggio che ti abbiamo inviato.<br/>
 Se hai seguito un link ed hai ottenuto questo errore, per favore,
 assicurati di avere inserito tutto il link nella barra degli indirizzi del
 tuo browser. A volte può succedere che i link contenuti nei messaggi
 emails siano spezzati su più righe.</p>
 <p>Se non conosci l'indirizzo esatto, puoi richiedere una emaile te lo
 indichi. Per favore, inserisci la tua email nel campo seguente e clicca su '" . $strContinue . "'
";
$strPersonalLocationSent = '<h1>Eseguito! Dovresti ricevere a breve un messaggio email con il tuo link personale</h1>';

?>
