<?

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nome';
$strAddress             = 'Morada';
$strEmail               = 'Email';
$strTown                = 'Localidade';
$strPostcode            = 'C&oacute;digo Postal';
$strSubscribeInfo       = 'Use o formul&aacute;rio em baixo para subscrever as nossas NewsLetters';
$strRequired            = 'Campo obrigat&oacute;rio';
$strSubscribeTitle      = 'Subscreva as nossas NewsLetters';
$strPleaseSelect        = 'Escolha as NewsLetters que pretende subscrever';
$strSubmit              = 'Enviar';
$strNotAvailable        = 'Lamentamos, mas ainda não existem NewsLetters dispon&iacute;veis.';
$strEnterName           = 'Tem que indicar o seu nome';
$strEnterEmail          = 'Tem que indicar o seu email';
$strInvalidHostInEmail  = 'Erro! Não foi encontrado nenhum host para enviar o seu email; controle se o seu email é correcto';
$strEnterList           = 'Tem que escolher pelo menos uma NewsLetter a subscrever';
$strPleaseEnter         = 'Por favor indique';
$strThanks              = 'Obrigado pela sua subscrição.';
$strEmailConfirmation   = 'Em poucos instantes receber&aacute; um email confirmando a(s) NewsLetter(s) que subscreveu.';
$strUnsubscribeTitle    = 'Cancelar a subscrição de uma ou v&aacute;rias NewsLetters';
$strUnsubscribeDone     = 'Foi removido da(s) NewsLetter(s) seleccionada(s). Dentro de instantes receber&aacute; um email de confirmação.';
$strBack                = 'Voltar atr&aacute;s';
$strUnsubscribeInfo     = 'Cancelar a subscrição de uma ou v&aacute;rias NewsLetters';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Escolha a(s) NewsLetter(s) que deseja deixar de receber';
$strAllLists            = 'Todas as NewsLetters';
$strNoLists             = 'Nenhuma';
$strNoListsFound        = 'Erro! Não existem nenhumas NewsLetters subscrevidas com este email.';
$strResubmit            = 'Re-enviar o email';
$strUnsubscribeSubmit   = 'Cancelar a subscrição das NewsLetters seleccionadas.';
$strValuesMissing       = 'Não preencheu os seguintes dados obrigat&oacute;rios';
$strConfirmInfo         = 'Obrigado pela confirmação da sua subscrição. Em baixo encontram-se listadas as NewsLetters que subscreveu.';
$strConfirmTitle        = 'P&aacute;gina de confirmação';
$strUserNotFound        = 'Assinante não encontrado';
$strConfirmFailInfo     = 'Erro ao tentar confirmar a sua subscrição. A mensagem de erro &eacute; indicada em baixo.';
$strPreferHTMLEmail     = 'SIM, enviem-me as NewsLetters no formato HTML';
$strPreferencesTitle    = 'Actualizar os seus dados';
$strPreferencesInfo     = 'Controle se a informação em baixo &eacute; correcta e clique "Actualizar".';
$strUpdatePreferences   = 'Actualizar';
$strPreferencesEmailChanged = 'O seu email for alterado. Por favor visite o link indicado no email que vai receber a fim de confirmar o seu novo email.';
$strPreferencesNotificationSent = 'Receber&aacute; um email contendo todas as alterações efectuadas.';
$strPreferencesUpdated = 'Obrigado pela suas submissão. Os seus dados foram actualizados.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'este link';
$strToUnsubscribe      = 'Para cancelar a subscrição desta NewsLetter visite';
$strToUpdate           = 'Para actualizar os seus dados visite';
$strSendHTML           = 'Enviar email em HTML';
$strYes                = 'Sim';
$strNo                 = 'Não';
$strUnsubscribe        = 'Cancelar subscrições';

?>
