<?php

# language dependent text used in the interface for users (not admin)
# contributed by Igor Guskow igor@suplementa.com.br
# Brazilian Portuguese

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nome';
$strAddress             = 'Endereço';
$strEmail               = 'Email';
$strTown                = 'Cidade';
$strPostcode            = 'CEP';
$strSubscribeInfo       = 'Inscreva-se em uma ou mais listas de email no formulário abaixo';
$strRequired            = 'campo necessário';
$strSubscribeTitle      = 'Inscreva-se em nossas listas de email';
$strPleaseSelect        = 'Por favor, escolha as listas em que você deseja cadastrar-se';
$strSubmit              = 'Inscreva-se nas listas selecionadas';
$strNotAvailable        = 'Perdão, não há listas disponíveis nesse momento';
$strEnterName           = 'Por favor, forneça seu nome';
$strEnterEmail          = 'Por favor, forneça seu email';
$strInvalidHostInEmail  = 'É impossível enviar emails para este domínio! Verifique se você digitou corretamente o endereço.';
$strEnterList           = 'Por favor, escolha a lista em que você deseja inscrever-se';
$strPleaseEnter      = 'Por favor, forneça seu';
$strThanks              = 'Obrigado por inscrever-se em nossas listas';
$strEmailConfirmation   = 'Em breve você receberá um email solicitando que você confirme a inscrição.';
$strEmailFailed          = 'O envio do email de confirmação da inscrição falhou. Clique em "Atualizar" para nova tentativa. Se falhar novamente, talvez você esteja cadastrado na "lista negra", o que impediria você de receber emails enviados pelo sistema. Se for este o caso, por favor, entre em contato conosco.';
$strUnsubscribeTitle    = 'Descadastre-se de nossas listas';
$strUnsubscribeDone     = 'Você foi descadastrado das listas que você selecionou. Em breve receberá um email para a confirmação do cancelamento.';
$strBack                = 'Voltar';
$strUnsubscribeInfo     = 'Descadastre-se de uma de nossas listas de email';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor, escolha as listas que você deseja se descadastrar';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma delas';
$strUnsubscribeRequestForReason = 'Lamentamos que você não queira mais receber nossas mensagens. A fim de melhorarmos a qualidade dos nossos serviços, ficariamos agradecidos se você nos dissesse o motivo da sua decisão';
$strUnsubscribeFinalInfo = '<br/><b>IMPORTANTE</b>: esta página tem como função remover seu email do nosso sistema <b>para sempre</b>. Se você deseja somente alterar o seu endereço de email, ou mudar alguma outra informação, por favor, acesse a página de <a href="[PREFERENCESURL]">atualização de dados</a> para isto.';
$strNoListsFound        = 'Perdão, você não está cadastrado em nenhuma de nossas listas com esse email';
$strResubmit            = 'Reenviar email';
$strUnsubscribeSubmit   = 'Descadastrar-se da lista selecionada';
$strValuesMissing       = 'As seguintes informações são necessárias';
$strConfirmInfo     = 'Obrigado por confirmar sua inscrição em nossas listas. Abaixo, a(s) lista(s) em que você se inscreveu';
$strConfirmTitle     = 'Página de confirmação de Inscrição';
$strUserNotFound    = 'Usuário não encontrado';
$strUserAlreadyInitialised = 'Sua senha já foi definida anteriormente';
$strConfirmFailInfo    = 'Sua inscrição não foi localizada no sistema. Certifique-se que você usou o endereço de página completo como informado no email enviado. Algumas vezes o endereço se extende por várias linhas.';
$strPreferHTMLEmail     = 'Quero receber as mensagens no formato HTML';
$strPreferTextEmail     = 'Quero receber as mensagens no formato TEXTO';
$strPreferredFormat      = 'Formatos possíveis para as mensagens enviadas:';
$strText                 = 'Texto';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Atualize suas informações';
$strPreferencesInfo     = 'Verifique se as informações abaixo estão corretas e clique no botão "Atualizar"';
$strUpdatePreferences   = 'Atualizar';
$strPreferencesEmailChanged = 'Seu endereço de email mudou. Visite a página apontada pelo link do email que você vai receber para confirmar o seu novo email.';
$strYouAreBlacklisted = 'Seu email consta na "Lista Negra", o que significa que você solicitou que nenhuma mensagem de nossas listas fosse enviada para o seu endereço. <br/>
Para receber nossas mensagens novamente é necessário que o administrador do sistema intervenha diretamente. Por favor, entre diretamente em contato conosco para nos informar que você deseja receber novamente nossas mensagens.';
$strPreferencesNotificationSent = 'Você receberá uma mensagem com as mudanças';
$strPreferencesUpdated = 'Suas informações foram atualizadas.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'este link';
$strToUnsubscribe      = 'Se você deseja parar de receber nossas mensagens,';
$strToUpdate           = 'Para atualizar suas informações e para cancelar sua inscrição acesse';
$strSendHTML           = 'Enviar mensagem HTML';
$strYes                = 'Sim';
$strNo                 = 'Não';
$strUnsubscribe        = 'Cancelar inscrição';
$strAllMailinglists    = 'Todas as listas';
$strAttachmentIntro     = 'Esta mensagem tem arquivos anexados que podem ser vistos via browser:';
$strLocation           = 'Local';
$strFrequency           = 'Freqüência com que devemos enviar as mensagens';
$strHourly             = 'De hora em hora';
$strDaily               = 'Diariamente';
$strWeekly             = 'Semanalmente';
$strMonthly             = 'Mensalmente';
$strChoosePassword      = 'Por favor, escolha uma senha';
$strConfirmPassword    = 'Confirme sua senha';
$strEnterPassword       = 'Digite sua senha';
$strForgotPassword     = 'Esqueceu a senha?';
$strPassword           = 'Senha';
$strPassword2           = 'Confirme sua senha';
$strPasswordsNoMatch    = 'Senhas diferentes';
$strEmailsNoMatch     = 'O endereço de email digitado não foi encontrado';
$strInvalidPassword     = 'Erro: email ou senha inválidos';
$strPasswordSent        = 'Sua senha foi enviada por email. Você deve estar recebendo-a em alguns minutos';
$strPasswordRemindSubject = 'Sua senha de acesso ao sistema';
$strPasswordRemindMessage = 'Sua senha é ';
$strPasswordRemindInfo = 'Para receber sua senha por email, digite seu endereço de email e clique no botão "'.$strForgotPassword.'".';
$strLogin               = 'Login';
$strLoginTitle          = 'Digite seu endereço de email e sua senha';
$strLoginInfo           = 'O acesso a esta página requer uma senha. Digite seu endereço de email e senha';
$strPersonalLocationInfo = '
  <p>O acesso a esta página requer a sua identificação pessoal, que pode ser encontrada nas mensagens enviadas a você pelo sistema.<br/>
    Se você clicou em um link e chegou até aqui, certifique-se que o link estava completo. Pode acontecer de que o link foi quebrado em diversas linhas.</p>
        <p>Se você não sabe o link completo, você pode solicitar que o mesmo seja enviado para você via email.
	  Digite seu email e clique em "Continuar"';
$strPersonalLocationSent = '<h1>Você deve estar recebendo uma mensagem com o link de sua identificação pessoal em breve</h1>';
$strUserExists   = '<br/>Este endereço de email já está cadastrado no sistema com uma senha diferente';
$strUserExistsExplanationStart = '<br/>Para obter sua senha clique ';
$strUserExistsExplanationLink = 'aqui';
$strUserExistsExplanationEnd = ' e você será direcionado à página onde poderá requisitar suas informações pessoais';
$strForwardTitle = 'Reenviar a mensagem para alguém';
$strForwardSubtitle = 'Reenviando a mensagem com assunto ';
$strForwardEnterEmail = 'Por favor, entre com um endereço de email válido para o reenvio';
$strForwardSuccessInfo ='A mensagem foi reenviada';
$strForwardFailInfo = 'Reenvio falhou';
$strForwardAlreadyDone = 'Esta mensagem já foi reenviada para este endereço anteriormente';
$strForwardFooter = 'Esta mensagem foi enviada a você por [FORWARDEDBY].
  Você não foi adicionado a esta lista. Se você desejar inscrever-se, acesse';
$strForward = 'Reenviar';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
