<?php

# language dependent text used in the interface for users (not admin)
# contributed by Igor Guskow igor@suplementa.com.br
# Brazilian Portuguese

$strName                = 'Nome';
$strAddress             = 'Endereço';
$strEmail               = 'Email';
$strTown                = 'Cidade';
$strPostcode            = 'CEP';
$strSubscribeInfo       = 'Inscreva-se em uma ou mais listas de email utilizando-se do formulário abaixo';
$strRequired            = 'campo necessário';
$strSubscribeTitle      = 'Inscreva-se em nossas listas de email';
$strPleaseSelect        = 'Por favor, escolha as listas em que você deseja cadastrar-se';
$strSubmit              = 'Inscreva-se nas listas selecionadas';
$strNotAvailable        = 'Perdão, não há listas disponíveis nesse momento';
$strEnterName           = 'Por favor, forneça seu nome';
$strEnterEmail          = 'Por favor, forneça seu email';
$strEnterList           = 'Por favor, escalha a lista na qual deseja inscrever-se';
$strPleaseEnter			= 'Por favor, forneça seu';
$strThanks              = 'Obrigado por inscrever-se em nossas listas';
$strEmailConfirmation   = 'Em breve você receberá um email confirmando em quais listas você se inscreveu.';
$strUnsubscribeTitle    = 'Descadastre-se de nossas listas';
$strUnsubscribeDone     = 'Você foi descadastrado das listas que você selecionou. Em breve receberá um email de confirmação.';
$strBack                = 'Voltar';
$strUnsubscribeInfo     = 'Descadastre-se de uma de nossas listas de email';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor, escolha as listas das quais deseja se descadastrar';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma delas';
$strNoListsFound        = 'Perdão, você não está cadastrado em nenhuma de nossas listas com esse email';
$strResubmit            = 'Enviar email novamente';
$strUnsubscribeSubmit   = 'Descadastrar-se da lista selecionada';
$strValuesMissing       = 'As seguintes informações são necessárias';
$strConfirmInfo 		= 'Obrigado por confirmar sua inscrição em nossas listas de email. Abaixo, a(s) lista(s) em que você se inscreveu';
$strConfirmTitle 		= 'Página de confirmação de usuário PHPlist';
$strUserNotFound		= 'Usuário não encontrado';
$strConfirmFailInfo		= 'Perdão, um erro ocorreu no momento de confirmação de sua inscrição. Segue-se abaixo a mensagem descritiva do erro.';

?>