<?

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nome';
$strAddress             = 'Morada';
$strEmail               = 'Correio Electr&oacute;nico';
$strTown                = 'Localidade';
$strPostcode            = 'C&oacute;digo Postal';
$strSubscribeInfo       = 'Use o formul&aacute;rio abaixo para subscrever uma ou mais das nossas listas de distribui&ccedil;&atilde;o';
$strRequired            = 'campo obrigat&oacute;rio';
$strSubscribeTitle      = 'Subscreva as nossas listas de distribui&ccedil;&atilde;o';
$strPleaseSelect        = 'Por favor seleccione a(s) lista(s) que pretende subscrever';
$strSubmit              = 'Subscreva as listas seleccionadas';
$strNotAvailable        = 'Lamentamos, mas ainda n&atilde;o existem listas dispon&iacute;veis.';
$strEnterName           = 'Por favor insira o seu nome';
$strEnterEmail          = 'Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico';
$strInvalidHostInEmail  = 'Lamentamos mas n&atilde;o conseguimos entregar correio electr&oacute;nico no dom&iacute;nio indicado. Por favor certifique-se que introduziu correctamente o seu endere&ccedil;o de correio electr&oacute;nico';
$strEnterList           = 'Por favor seleccione a lista que pretende subscrever';
$strPleaseEnter         = 'Por favor indique';
$strThanks              = 'Estimado(a) [FIRST NAME], <br/>Obrigado por subscrever a(s) nossa(s) listas de distribui&ccedil;&atilde;o';
$strEmailConfirmation   = 'O seu endere&ccedil;o de correio electr&oacute;nico [email] foi acrescentado ao nosso sistema. Em breve receber&aacute; uma mensagem com a confirma&ccedil;&atilde;o da(s) lista(s) que subscreveu. Por favor certifique-se que clica na liga&ccedil;&atilde;o enviada nessa mensagem para confirmar a sua subscri&ccedil;&atilde;o.';
$strEmailFailed			= 'Lamentamos mas n&atilde;o conseguimos enviar-lhe o correio electr&oacute;nico solicitando a sua confirma&ccedil;&atilde;o. Por favor clique o bot&atilde;o "<em>Reload</em>" ou "Refrescar" para tentar novamente.';
$strUnsubscribeTitle    = 'Cancelar a sua subscri&ccedil;&atilde;o da(s) nossa(s) lista(s) de distribui&ccedil;&atilde;o';
$strUnsubscribeDone     = 'Procedemos ao cancelamento da sua subscri&ccedil;&atilde;o da(s) lista(s) de distribui&ccedil;&atilde;o seleccionada(s) e brevemente receber&aacute; uma confirma&ccedil;&atilde;o por correio electr&oacute;nico.';
$strBack                = 'Voltar atr&aacute;s';
$strUnsubscribeInfo     = 'Cancelar a subscri&ccedil;&atilde;o de uma ou v&aacute;rias das nossas listas de distribui&ccedil;&atilde;o';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor seleccione a(s) lista(s) cuja subscri&ccedil;&atilde;o pretende cancelar.';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma das listas';
$strNoListsFound        = 'Lamentamos, mas este endere&ccedil;o de correio electr&oacute;nico n&atilde;o se encontra nas bases de dados de assinantes de nenhuma das nossas listas.';
$strResubmit            = 'Reenviar correio electr&oacute;nico';
$strUnsubscribeSubmit   = 'Cancelar a subscri&ccedil;&atilde;o da(s) lista(s) seleccionada(s).';
$strValuesMissing       = 'N&atilde;o preencheu os seguintes dados obrigat&oacute;rios';
$strConfirmInfo         = 'Obrigado pela confirma&ccedil;&atilde;o da sua subscri&ccedil;&atilde;o. A(s) lista(s) que subscreve encontra(m)-se listada(s) abaixo.';
$strConfirmTitle        = 'P&aacute;gina de confirma&ccedil;&atilde;o da subscri&ccedil;&atilde;o';
$strUserNotFound        = 'Assinante n&atilde;o encontrado';
$strUserAlreadyInitialised = 'Lamentamos, mas a sua palavra-chave j&aacute; foi definida';
$strConfirmFailInfo     = 'Lamentamos, mas o seu pedido de confirma&ccedil;&atilde;o n&atilde;o foi reconhecido. Certifique-se que usa a totalidade do endere&ccedil;o conforme este surge na mensagem de correio electr&oacute;nico que lhe foi enviada. Por vezes, esse endere&ccedil;o &eacute; quebrado em duas linhas.';
$strPreferHTMLEmail     = 'Eu prefiro receber mensagens no formato HTML';
$strPreferTextEmail     = 'Eu prefiro receber mensagens no formato Texto';
$strPreferredFormat		= 'Formato preferido:';
$strText 				= 'Texto';
$strHTML				= 'HTML';
$strPreferencesTitle    = 'Actualize os seus dados';
$strPreferencesInfo     = 'Por favor confirme se a informa&ccedil;&atilde;o abaixo est&aacute; correcta e clique no bot&atilde;o "Actualizar".';
$strUpdatePreferences   = 'Actualizar';
$strPreferencesEmailChanged = 'O seu endere&ccedil;o de correio electr&oacute;nico foi alterado. Por favor visite o endere&ccedil;o indicado na mensagem que vai receber por correio electr&oacute;nico, para confirmar o seu novo endere&ccedil;o.';
$strPreferencesNotificationSent = 'Receber&aacute; uma mensagem por correio electr&oacute;nico contendo as altera&ccedil;&otilde;es efectuadas.';
$strPreferencesUpdated = 'Obrigado pela actualiza&ccedil;&atilde;o. Os seus dados foram actualizados.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'esta liga&ccedil;&atilde;o';
$strToUnsubscribe      = 'Para cancelar a subscri&ccedil;&atilde;o desta lista visite';
$strToUpdate           = 'Para actualizar os seus dados visite';
$strSendHTML           = 'Enviar correio electr&oacute;nico em HTML';
$strYes                = 'Sim';
$strNo                 = 'N&atilde;o';
$strUnsubscribe        = 'Cancelar subscri&ccedil;&otilde;es';
$strAttachmentIntro	   = 'Esta mensagem cont&eacute;m anexos que podem ser vistos com um <em>web browser</em>:';
$strLocation		   = 'Endere&ccedil;o/URL';
$strFrequency		   = 'Com que frequ&ecirc;ncia lhe enviamos mensagens';
$strHourly			   = 'Hora a hora';
$strDaily			   = 'Diariamente';
$strWeekly			   = 'Semanalmente';
$strMonthly			   = 'Mensalmente';
$strChoosePassword 	   = 'Por favor escolha uma palavra-chave';
$strConfirmPassword    = 'Confirme a sua palavra-chave';
$strEnterPassword	   = 'Por favor introduza a sua palavra-chave';
$strForgotPassword	   = 'Esqueci-me da palavra-chave';
$strPassword		   = 'Palavra-chave';
$strPassword2		   = 'Confirmar palavra-chave';
$strPasswordsNoMatch   = 'As palavras-chave n&atilde;o condizem';
$strInvalidPassword	   = 'Erro: endere&ccedil;o de correio electr&oacute;nico ou palavra-chave inv&aacute;lidos';
$strPasswordSent 	   = 'A sua palavra-chave foi enviada para o seu endere&ccedil;o de correio electr&oacute;nico. Dever&aacute; receb&ecirc;-la dentro de momentos';
$strPasswordRemindSubject = 'A sua palavra-chave para as nossas listas';
$strPasswordRemindMessage = 'A sua palavra-chave é ';
$strPasswordRemindInfo = 'Para receber a sua palavra-chave por correio electr&oacute;nico, por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e clique no bot&atilde;o "'.$strForgotPassword.'"';
$strLogin			   = 'Login';
$strLoginTitle 		   = 'Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e palavra-chave';
$strLoginInfo		   = 'Esta p&aacute;gina requere uma palavra-chave. Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e a palavra-chave';
$strPersonalLocationInfo = '
	<p>Para aceder a esta p&aacute;gina &eacute; necess&aacute;ria uma identifica&ccedil;&atilde;o pessoal que pode ser encontrada em cada mensagem que lhe enviamos.<br/>
  Se clicou neste endere&ccedil;o <em>web</em> e se obteve este erro, por favor certifique-se que coloca a totalidade do endere&ccedil;o no seu <em>browser</em>. Por vezes, os programas de correio electr&oacute;nico quebram este endere&ccedil;o em mais de uma linha.</p>
  <p>Se n&atilde;o conhece esse endere&ccedil;o <em>web</em>, pode solicitar o envio de uma mensagem que lho dar&aacute; a conhecer.
  Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico no campo e clique "Continuar"
';
$strPersonalLocationSent = '<h1>Sucesso! Dever&aacute; receber a mensagem com o seu endere&ccedil;o/URL pessoal dentro de momentos</h1>';

?>
