<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'Windows-1251';
$strName                = 'Имя';
$strAddress             = 'Адрес';
$strEmail               = 'Email';
$strTown                = 'Город';
$strPostcode            = 'Индекс';
$strSubscribeInfo       = 'Подпишитесь на рассылки с помощью формы';
$strRequired            = 'обязательное поле';
$strSubscribeTitle      = 'Подпишитесь на рассылки';
$strPleaseSelect        = 'Пожалуйста, выберите рассылки, на которые хотите подписаться';
$strSubmit              = 'Подписаться на выбранные рассылки';
$strNotAvailable        = 'Рассылки не доступны';
$strEnterName           = 'Введите ваше имя';
$strEnterEmail          = 'Введите адрес email';
$strInvalidHostInEmail  = 'Невозможно доставить почту по адресу, пожалуйста, убедитесь в его правильности';
$strEnterList           = 'Выберите рассылку';
$strPleaseEnter         = 'Введите ваш';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Спасибо что подписались на рассылки.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Ваш адрес добавлен в систему. В скором времени вам должен прийти запрос на подтверждение. Не забудьте перейти по указанной там ссылке для подтверждения подписки.';
$strEmailFailed          = 'Извините, не удалось отправить запрос на подтверждение вашей подписки, перезагрузите страницу и попробуйте снова. Если это не поможет, свяжитесь с администратором.';
$strUnsubscribeTitle    = 'Отписка от рассылок';
$strUnsubscribeDone     = 'Вы отписались от рассылок и получите подтверждение в скором времени.';
$strBack                = 'Назад';
$strUnsubscribeInfo     = 'Отписка от рассылок';
$strContinue            = 'Продолжить';
$strUnsubscribeSelect   = 'Выберите рассылки, от которых хотите отписаться';
$strAllLists            = 'Все рассылки';
$strNoLists             = 'Ни одной рассылки';
$strUnsubscribeRequestForReason = 'Сожалеем что вы не заинтересованы более в наших рассылках. Мы были бы очень благодарны, если бы вы рассказали почему:';
$strUnsubscribeFinalInfo = '<br/><b>Заметьте</b>: эта страница предназначена чтобы перестать получать наши рассылки <b>навсегда</b>. Если вы хотите изменить адрес электронной почты или рассылки, которые получаете, <a href="[PREFERENCESURL]">измените ваши настройки</a>';
$strNoListsFound        = 'Извините, вы не подписаны ни на одну из наших рассылок с этим адресом';
$strResubmit            = 'Подтвердите Email';
$strUnsubscribeSubmit   = 'Отписаться от выбранных рассылок';
$strValuesMissing       = 'Следующие обязательные поля не заполнены';
$strConfirmInfo         = 'Спасибо за подтверждение подписки. Рассылки, на которые вы подписались, перечислены ниже';
$strConfirmTitle        = 'Подтверждение подписки';
$strUserNotFound        = 'Пользователь не найден';
$strUserAlreadyInitialised = 'Извините, ваш пароль уже установлен';
$strConfirmFailInfo     = 'Извините, ваш запрос на подтверждение не распознан. Пожалуйста, убедитесь что вы используете запрос полностью как он указан в письме. Иногда запросы переносятся на несколько строчек.';
$strPreferHTMLEmail     = 'Получать письма в формате HTML';
$strPreferTextEmail     = 'Получать письма в виде текста';
$strPreferredFormat      = 'Предпочитаемый формат писем:';
$strText                 = 'Текст';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Обновите ваши настройки';
$strPreferencesInfo     = 'Проверьте что данные верны и нажмите кнопку "Обновить"';
$strUpdatePreferences   = 'Обновить';
$strPreferencesEmailChanged = 'Адрес email изменен, выслано письмо с подтверждением. Перейдите по ссылке, которая будет указана в письме для подтверждения вашего нового адреса';
$strYouAreBlacklisted = 'Ваш адрес внесен в "Черный Список" и вы не можете подписываться на рассылки. Если вы считаете, что это произошло по ошибке, свяжитесь с администратором.';
$strPreferencesNotificationSent = 'Вам выслано письмо с указанием изменений';
$strPreferencesUpdated = 'Спасибо. Мы обновили информацию.';
$strClickHere          = 'Нажмите здесь';
$strThisLink           = 'эту ссылку';
$strToUnsubscribe      = 'Если вы более не хотите получать рассылки, ';
$strToUpdate           = 'Для обновления ваших настроек посетите';
$strSendHTML           = 'Отправить письмо в HTML';
$strYes                = 'Да';
$strNo                 = 'Нет';
$strUnsubscribe        = 'Отписаться';
$strAllMailinglists    = 'Все рассылки';
$strAttachmentIntro     = 'это письмо содержит вложения, которые могут быть просмотрены с помощью браузера:';
$strLocation           = 'Адрес';
$strFrequency           = 'Как часто высылать письма';
$strHourly             = 'Ежечасно';
$strDaily               = 'Ежедневно';
$strWeekly             = 'Еженедельно';
$strMonthly             = 'Ежемесячно';
$strChoosePassword      = 'Выберите пароль';
$strConfirmPassword    = 'Подтвердите пароль';
$strEnterPassword       = 'Введите пароль';
$strForgotPassword     = 'Забыли пароль?';
$strPassword           = 'Пароль';
$strPassword2           = 'Подтвердите пароль';
$strPasswordsNoMatch    = 'Пароли не совпадают';
$strEmailsNoMatch     = 'Адреса email не совпадают';
$strInvalidPassword     = 'Ошибка: неправильный email или пароль';
$strPasswordSent        = 'Ваш пароль выслан вам по почте. Вы должны получить его через несколько минут';
$strPasswordRemindSubject = 'Ваш пароль для рассылок';
$strPasswordRemindMessage = 'Ваш пароль: ';
$strPasswordRemindInfo = 'Чтобы получить пароль по почте, введите свой email и нажмите кнопку "'.$strForgotPassword.'".';
$strLogin               = 'Login';
$strLoginTitle          = 'Введите свой адрес email и пароль';
$strLoginInfo           = 'Эта страница требует регистрации. Введите свой email и пароль';
$strPersonalLocationInfo = '
  <p>Эта страница тербует адреса персональной идентификации, который мы высылаем вам с каждым письмом.<br/>
  Если вы нажали на этот адрес и видите эту страницу, то, скорее всего, адрес был неполным, так как иногда
  адреса разбиваются на несколько строчек.</p>
  <p>Если вы не знаете нужного адреса, то вы можете получить email с его указанием.
  Введите адрес email внизу и нажмите "Продолжить"
';
$strPersonalLocationSent = '<h1>Письмо с адресом должно прийти в скором времени</h1>';
$strUserExists   = '<br/>В базе данных содержится пользователь с этим адресом email, но другим паролем';
$strUserExistsExplanationStart = '<br/>Чтобы получить пароль нажмите ';
$strUserExistsExplanationLink = 'здесь';
$strUserExistsExplanationEnd = ' чтобы перейти на страницу, где вы можете запросить персональный адрес настроек';
$strForwardTitle = 'Переслать письмо';
$strForwardSubtitle = 'Пересылается письмо с темой ';
$strForwardEnterEmail = 'Введите адрес для пересылки';
$strForwardSuccessInfo ='Письмо отправлено';
$strForwardFailInfo = 'Пересылка завершилась неудачно';
$strForwardAlreadyDone = 'Письмо уже было успешно переслано по этому адресу';
$strForwardFooter = 'Это письмо было отправлено вам [FORWARDEDBY].
  Вы не были автоматически подписаны на рассылку.
  Чтобы подписаться на рассылку перейдите ';
$strForward = 'Пересылка';
$strFwd = 'Fwd'; # short version of forward for email subject
?>