<?

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nombre';
$strAddress             = 'Dirección';
$strEmail               = 'Email';
$strTown                = 'Ciudad';
$strPostcode            = 'Código Postal';
$strSubscribeInfo       = 'Suscríbete a una o más de nuestras listas usando el siguiente formulario';
$strRequired            = 'Campo obligatorio';
$strSubscribeTitle      = 'Suscríbete a nuestras listas de correo';
$strPleaseSelect        = 'Por favor, selecciona las listas a las que deseas suscribirte';
$strSubmit              = 'Suscribirme';
$strNotAvailable        = 'Lo siento, actualmente no hay listas disponibles';
$strEnterName           = 'Por favor, introduce tu nombre';
$strEnterEmail          = 'Por favor, introduce tu dirección de correo';
$strInvalidHostInEmail  = 'Lo siento, pero no encuentro tu servidor, por favor, comprueba tu dirección de correo';
$strEnterList           = 'Por favor, selecciona la lista a la que te quieres suscribir';
$strPleaseEnter		= 'Por favor, introduce tu';
$strThanks              = 'Gracias por suscribirte a nuestras listas.';
$strEmailConfirmation   = 'En breve te llegará un e-mail con la confirmación de las listas a las que te has suscrito.';
$strEmailFailed		= 'Lo siento, hubo un fallo en el envío de tu confirmación. Por favor, pulsa "actualizar" para intentarlo de nuevo.';
$strUnsubscribeTitle    = 'Cancelar la suscripción a nuestras listas de correo';
$strUnsubscribeDone     = 'Has cancelado la suscripción a la lista que seleccionaste y recibirás una confirmación por e-mail.';
$strBack                = 'Atrás';
$strUnsubscribeInfo     = 'Cancelar la suscripción a nuestra(s) lista(s) de correo';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor, selecciona la lista de la que quieres cancelar tu suscripción';
$strAllLists            = 'Todas las Listas';
$strNoLists             = 'Ninguna';
$strNoListsFound        = 'Actualmente no estás suscrito a ninguna de nuestras listas de correo con esa dirección de correo';
$strResubmit            = 'Re-enviar e-mail';
$strUnsubscribeSubmit   = 'Cancelar suscripción de las listas de correo seleccionadas';
$strValuesMissing       = 'El siguiente valor obligatorio no fue introducido';
$strConfirmInfo 	= 'Gracias por confirmar tu suscripción a nuestras listas. Las listas a las que te has suscrito se muestran a continuación';
$strConfirmTitle 	= 'Página de confirmación para los miembros';
$strUserNotFound	= 'Usuario no encontrado';
$strConfirmFailInfo	= 'Un error ha ocurrido al tratar de confirmar tu suscripción. El mensaje de error se muestra a continuación.';
$strPreferHTMLEmail     = 'Prefiero recibir emails en formato HTML';
$strPreferTextEmail     = 'Prefiero recibir emails en formato Texto';
$strPreferredFormat	= 'Formato preferido para los emails:';
$strText 		= 'Texto';
$strHTML		= 'HTML';
$strPreferencesTitle    = 'Actualiza tus preferencias';
$strPreferencesInfo     = 'Por favor, confirma que la información es correcta y pulsa el botón "Actualizar información"';
$strUpdatePreferences   = 'Actualizar información';
$strPreferencesEmailChanged = 'Tu email haa cambiado. Por favor, visita el enlace en el email que recibirás para confirmar tu nueva dirección';
$strPreferencesNotificationSent = 'Recibirás un email con los cambios';
$strPreferencesUpdated = 'Gracias. Hemos actualizado tu información.';
$strClickHere          = 'Pulsa aquí';
$strThisLink           = 'este enlace';
$strToUnsubscribe      = 'Para borrarte de esta lista visita';
$strToUpdate           = 'Para actualizar tus preferencias visita';
$strSendHTML           = 'Enviar correo HTML';
$strYes                = 'Sí';
$strNo                 = 'No';
$strUnsubscribe        = 'Dar de baja';

?>
