<?php

# language dependent text used in the interface for users (not admin)
# translation by Björn Pålsson <sm7wqo@sk7dd.com>
# translated for version 1.9.3

$strName                = 'Nam';
$strAddress             = 'Adress';
$strEmail               = 'E-post';
$strTown                = 'Ort';
$strPostcode            = 'Postnr';
$strSubscribeInfo       = 'Anmäl dig till en eller flera av våra listor genom att fylla i formuläret nedan.';
$strRequired            = 'Oligatoriskt fält';
$strSubscribeTitle      = 'Anmäl dig till en av våra listor';
$strPleaseSelect        = 'Välj de listor du önskar att anmäla dig till';
$strSubmit              = 'Anmäl de valda listorna';
$strNotAvailable        = 'Beklager, det finns inga listor tilgängliga';
$strEnterName           = 'Skriv in ditt namn';
$strEnterEmail          = 'Skriv in din E-post adress';
$strEnterList           = 'Välj en lista du önskar att anmäla dig till';
$strThanks              = 'Tack för att du har anmält dig till en af vore listor.';
$strEmailConfirmation   = 'Du kommer snart att få ett E-mail med en bekräftelse på de listor du anmält dig till';
$strUnsubscribeTitle    = 'Avanmäl dig från en av våra listor';
$strUnsubscribeDone     = 'Du er avanmäld från de valda listorna. Du kommer att få en bekräftelse inom kort.';
$strBack                = 'Tillbaka';
$strUnsubscribeInfo     = 'Avanmäl dig från en eller flera av våra listor';
$strContinue            = 'Fortsätt';
$strUnsubscribeSelect   = 'Välj de listor du önskar att avanmäla dig från';
$strAllLists            = 'Alla listor';
$strNoLists             = 'Ingen av dem';
$strNoListsFound        = 'Beklagar, du är inte anmäld till några av våra listor med den E-mailadressen';
$strResubmit            = 'Skicka E-mail igen';
$strUnsubscribeSubmit   = 'Avanmäl de valda listorna';
$strValuesMissing       = 'De följande obligatoriska fälten saknas';
$strConfirmInfo                 = 'Tack för bekräftelsen på anmälan till våra listor. De listor du har anmält dig till visas nedan';
$strConfirmTitle                = 'PHPlist bekräftelse på anmälan';

?>