<?php

# language dependent text used in the interface for users (not admin)
# translated by Seref Erkayhan erkayhan@fzi.de

$strCharSet             = 'ISO-8859-9';
$strName                = 'Ýsim';
$strAddress             = 'Adress';
$strEmail               = 'Email';
$strTown                = 'Þehir';
$strPostcode            = 'Posta kodu';
$strSubscribeInfo       = 'Hangi eMail-Listelerine katýlmak istediðinizi seçiniz';
$strRequired            = 'Gerekli alan | Benötigte Felder | Necessary fields';
$strSubscribeTitle      = 'eMail-Listemize üye olunuz';
$strPleaseSelect        = 'Lütfen üye olmak istediðiniz eMail-Listemizi seçiniz | Wählen Sie bitte die Liste | Please chose the list ';
$strSubmit              = 'Gönderiniz | Senden | Submit';
$strNotAvailable        = 'Üzgünüz þu an üye olacaðýnýz eMail-Listemiz yoktur';
$strEnterName           = 'Lütfen isminizi giriniz';
$strEnterEmail          = 'Lütfen eMail adresinizi giriniz';
$strInvalidHostInEmail  = 'Üzgünüz, eMailinizi gönderecek sunucu yok, lütfen eMail adresinizi kontrol ediniz';
$strEnterList           = 'Üye olmak istediðiniz eMail-Listemizi seçiniz';
$strPleaseEnter         = 'Lütfen giriniz';
$strThanks              = 'Listemize üye olduðunuz için teþekkürler';
$strEmailConfirmation   = 'Listemize katýlýmýnýzý doðrulamanýz için eMail gönderildi.';
$strUnsubscribeTitle    = 'Listemizden çýkmanýz için buraya týklayýnýz';
$strUnsubscribeDone     = 'Listemizden çýktýnýz ve bunu doðrulamanýz için mail alacaksýnýz.';
$strBack                = 'Geri';
$strUnsubscribeInfo     = 'Listemiz veya listelerimizden çýkmanýz için buraya týklayýnýz';
$strContinue            = 'Devam ediniz';
$strUnsubscribeSelect   = 'Lütfen çýkmak istediðiniz Listeyi seçiniz';
$strAllLists            = 'Tüm Listeler';
$strNoLists             = 'Hiçbiri';
$strNoListsFound        = 'Üzgünüz, bu email adresi ile hiç bir listemize üye deðilsiniz';
$strResubmit            = 'Email adresinizi tekrar giriniz';
$strUnsubscribeSubmit   = 'Seçtiðiniz listeden çýkmak için buraya týklayýnýz';
$strValuesMissing       = 'Aþaðýdaki gerekli veriler eksik';
$strConfirmInfo         = 'Listemize katýlýmýnýzý doðruladýðýnýz için teþekkürler. Katýldýðýnýz listeler aþaðýdadýr';
$strConfirmTitle        = 'Liste üyeliginizi doðrulama sayfasý';
$strUserNotFound        = 'Kullanýcý bulunamadý';
$strConfirmFailInfo     = 'Üzgünüz, üyeliðiniz sýrasýnda bir hata meydana geldi. Hata mesajý aþaðýdadýr.';
$strPreferHTMLEmail     = 'HTML formatýnda eMail tercih ederim | Ich bevorzuge eMails in HTML-Format | I prefer eMails in HTML Format';
$strPreferencesTitle    = 'Ayarlarýnýzý güncelleþtiriniz';
$strPreferencesInfo     = 'Lütfen aþaðýdaki bilgilerin doðruluðunu kontrol ediniz ve güncelleþtiriniz (Update)';
$strUpdatePreferences   = 'Güncelleþtirme (Update)';
$strPreferencesEmailChanged = 'Email adresiniz deðiþtirildi. Lütfen yeni eMail adresinizin deðiþikliðini doðrulamanýz için gönderilen eMaile cevap veriniz';
$strPreferencesNotificationSent = 'Deðiþiklikleri içeren bir eMail alacaksýnýz';
$strPreferencesUpdated = 'Teþekkürler. Verileriniz güncelleþtirildi';
$strClickHere          = 'Lütfen burayý týklayýnýz';
$strThisLink           = 'Bu link';
$strToUnsubscribe      = 'Bu listeyi terk etmek için týklayýnýz';
$strToUpdate           = 'Ayarlarýnýzý deðiþtirmek için týklayýnýz';
$strSendHTML           = 'HTML eMail gönderebilmeniz için';
$strYes                = 'Evet';
$strNo                 = 'Hayýr';
$strUnsubscribe        = 'eMail listesinden cýkmak için';

?>
