<?php 
$lan = array(
  "NoRecord" => "Nenhum registro",
  "BackToBList" => "Voltar para a lista de emails com problema",
  "NotFound" => "N&atildeo encontrado<br/>",
  "AddedToB" => "Adicionado %s ao contador de emails com problema pelo usu&aacuterio  %s<br/>",
  "NotAddedToB" => "N&atildeo pode adicionar %s ao contador de emails com problema pelo usu&aacuterio %s<br/>",
  "MadeUnconfirmed" => "Marcar usu&aacuterio %s  como n&atildeo confirmado<br/>",
  "MadeUserRText" => "Marcar o usu&aacuterio %s para receber o texto<br/>",
  "DelUser" => "Usu&aacuterio apagado %s<br/>",
  "DeletingB" => "Apagando email com problema %s ..\n",
  "DoneAndLoading" => "..Conclu&iacutedo, carregando pr&oacuteximo email com problema..",
  "NoSRecord" => "Nenhum Registro",
  "PossibleActions" => "A&ccedil&otildees Poss&iacuteveis:",
  "ForUser" => "Para usu&aacuterios com email",
  "IncreaseB" => "Aumentar o contador de emails com problema com",
  "IncreaseBNote" => "(use n&uacutemeros negativos para diminuir)",
  "MarkAsUnconfirmed" => "Marcar usu&aacuterio como n&atildeo confirmado",
  "MarkAsUnconfirmedNote" => "(ent&atildeo voc&ecirc pode reenviar o pedido de confirma&ccedil&atildeo)",
  "SetReceiveText" => "Definir que o usu&aacuterio deve receber mensagem tipo texto ao inv&eacutes de HTML",
  "DelUser1" => "Apagar usu&aacuterio",
  "DelAndGo" => "Apagar este email com problema e ir para o pr&oacuteximo",
  "DoAbove" => "Ir para anterior",
  "BounceDetails" => "Detalhes do Email com problema:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Coment&aacuterio",
  "Header" => "Cabe&ccedil&aacuterio",
  "Body" => "Corpo da mensagem",
);
?>
