<?php 
$lan = array(
  "NoRecord" => "Nenhum registro",
  "BackToBList" => "Voltar para a lista de emails com problema",
  "NotFound" => "N&atilde;o encontrado<br/>",
  "AddedToB" => "Adicionado %s ao contador de emails com problema pelo usu&aacute;rio  %s<br/>",
  "NotAddedToB" => "N&atilde;o pode adicionar %s ao contador de emails com problema pelo usu&aacute;rio %s<br/>",
  "MadeUnconfirmed" => "Marcar usu&aacute;rio %s  como n&atilde;o confirmado<br/>",
  "MadeUserRText" => "Marcar o usu&aacute;rio %s para receber o texto<br/>",
  "DelUser" => "Usu&aacute;rio apagado %s<br/>",
  "DeletingB" => "Apagando email com problema %s ..\n",
  "DoneAndLoading" => "..Conclu&iacute;do, carregando pr&oacute;ximo email com problema..",
  "NoSRecord" => "Nenhum Registro",
  "PossibleActions" => "A&ccedil;&otilde;es Poss&iacute;veis:",
  "ForUser" => "Para usu&aacute;rios com email",
  "IncreaseB" => "Aumentar o contador de emails com problema com",
  "IncreaseBNote" => "(use n&uacute;meros negativos para diminuir)",
  "MarkAsUnconfirmed" => "Marcar usu&aacute;rio como n&atilde;o confirmado",
  "MarkAsUnconfirmedNote" => "(ent&atilde;o voc&ecirc; pode reenviar o pedido de confirma&ccedil;&atilde;o)",
  "SetReceiveText" => "Definir que o usu&aacute;rio deve receber mensagem tipo texto ao inv&eacute;s de HTML",
  "DelUser1" => "Apagar usu&aacute;rio",
  "DelAndGo" => "Apagar este email com problema e ir para o pr&oacute;ximo",
  "DoAbove" => "Ir para anterior",
  "BounceDetails" => "Detalhes do Email com problema:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Estatus",
  "Comment" => "Coment&aacute;rio",
  "Header" => "Cabe&ccedil;&aacute;rio",
  "Body" => "Corpo da mensagem",
 
  # new in 2.9.5
  'Regular Expression' => 'Express&atilde;o recorrente',
  'Action' => 'A&ccedil;&atilde;o',
  'Memo for this rule' => 'Memo para esta regra',
  'Add new Rule' => 'Adicionar nova Regra',
  'Create New Rule based on this bounce' => 'Criar Nova Regra baseada neste email com problema',
);
?>
