<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Sua base de dados &eacute antiga, certifique-se de sua atualiza&ccedil;&atilde;o',
  'Your version' => 'Sua vers&atilde;o',
  'Latest version' => '&Uacute;ltima vers&atilde;o',
  'phplist version' => 'vers&atilde;o do <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'A base de dados n&atilde;o foi iniciada ',
  'go to' => 'ir para',
  'Initialise Database' => 'Iniciar a Base de Dados',
  'to continue' => 'continuar',
  'A new version of PHPlist is available!' => 'Uma nova vers&atilde;o do PHPlist est&aacute; dispon&iacute;vel!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'A nova vers&aacute;o pode ter corrigido falhas de seguran&ccedil;a,<br/>logo &eacute; recomendado fazer a atualiza&ccedil;&atilde;o o mais r&aacute;pido poss&iacute;vel',
  'View what has changed' => 'Veja o que mudou',
  'Download' => 'Baixar',
  'System Functions' => 'Fun&ccedil;&otilde;es do Sistema',
  'Setup ' => 'Configura&ccedil;&otilde;es',
  'Check Database structure' => 'Verificar a estrutura da Base de Dados',
  'View the eventlog' => 'Veja o registro de eventos',
  'Configuration functions' => 'Configura&ccedil;&atilde;o das fun&ccedil;&otilde;es',
  'Configure Attributes' => 'Configurar Atributos',
  'Control values for' => 'Controlar valores para',
  'Control values for' => 'Controlar valores para',
  'Control values for' => 'Controlar valores para',
  'Configure Subscribe pages' => 'Configurar p&aacute;ginas de Inscri&ccedil;&atilde;o',
  'List and user functions' => 'Fun&ccedil;&otilde;es da lista e dos usu&aacute;rios',
  'List the current lists' => 'Listar as listas atuais',
  'List all Users' => 'Listar todos os Usu&aacute;rios',
  'Reconcile the user database' => 'Corrigir a base de dados de usu&aacute;rios',
  'Import Users' => 'Importar Usu&aacute;rios',
  'Export Users' => 'Exportar Usu&aacute;rios',
  'Administrator functions' => 'Fun&ccedil;&otilde;es do Administrador',
  'Add, edit and remove Administrators' => 'Adicionar, editar e excluir Administradores',
  'Configure attributes for administrators' => 'Configurar atributos dos administradores',
  'Message functions' => 'Fun&ccedil;&otilde;es da Mensagem',
  'Configure Templates' => 'Configurar Modelos',
  'List all Messages' => 'Listar todas as Mensagens',
  'Process the Message queue' => 'Processar a fila de Mensagens',
  'RSS Functions' => 'Fun&ccedil;&otilde;es do RSS',
  'Get RSS feeds' => 'Obter arquivos RSS',
  'View RSS items' => 'Ver &iacute;tens RSS',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Atualizar',
'Change your details (e.g. password)' => 'Alterar seus dados (por exemplo, a senha)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Voc&ecirc; definiu o valor 1 para  TEST no seu config.php, logo s&oacute; ser&aacute; exibido o que seria enviado',

);

?>
