<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Sua base de dados &eacute antiga, certifique-se de sua atualiza&ccedil&atildeo',
  'Your version' => 'Sua vers&atildeo',
  'Latest version' => '&Uacuteltima vers&atildeo',
  'phplist version' => 'vers&atildeo do <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'A base de dados n&atildeo foi iniciada ',
  'go to' => 'ir para',
  'Initialise Database' => 'Iniciar a Base de Dados',
  'to continue' => 'continuar',
  'A new version of PHPlist is available!' => 'Uma nova vers&atildeo do PHPlist est&aacute dispon&iacutevel!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'A nova vers&aacuteo pode ter corrigido falhas de seguran&ccedila,<br/>logo &eacute recomendado fazer a atualiza&ccedil&atildeo o mais r&aacutepido poss&iacutevel',
  'View what has changed' => 'Veja o que mudou',
  'Download' => 'Baixar',
  'System Functions' => 'Fun&ccedil&otildeoes do Sistema',
  'Setup ' => 'Configura&ccedil&otildees',
  'Check Database structure' => 'Verificar a estrutura da Base de Dados',
  'View the eventlog' => 'Veja o registro de eventos',
  'Configuration functions' => 'Configura&ccedil&atildeo das fun&ccedil&otildeoes',
  'Configure Attributes' => 'Configurar Atributos',
  'Control values for' => 'Controlar valores para',
  'Control values for' => 'Controlar valores para',
  'Control values for' => 'Controlar valores para',
  'Configure Subscribe pages' => 'Configurar p&aacuteginas de Inscri&ccedil&atildeo',
  'List and user functions' => 'Fun&ccedil&otildees da lista e dos usu&aacuterios',
  'List the current lists' => 'Listar as listas atuais',
  'List all Users' => 'Listar todos os Usu&aacuterios',
  'Reconcile the user database' => 'Corrigir a base de dados de usu&aacuterios',
  'Import Users' => 'Importar Usu&aacuterios',
  'Export Users' => 'Exportar Usu&aacuterios',
  'Administrator functions' => 'Fun&ccedil&otildees do Administrador',
  'Add, edit and remove Administrators' => 'Adicionar, editar e excluir Administradores',
  'Configure attributes for administrators' => 'Configurar atributos dos administradores',
  'Message functions' => 'Fun&ccedil&otildees da Mensagem',
  'Configure Templates' => 'Configurar Modelos',
  'List all Messages' => 'Listar todas as Mensagens',
  'Process the Message queue' => 'Processar a fila de Mensagens',
  'RSS Functions' => 'Fun&ccedil&otildees do RSS',
  'Get RSS feeds' => 'Obter arquivos RSS',
  'View RSS items' => 'Ver &iacutetens RSS',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Atualizar',
'Change your details (e.g. password)' => 'Alterar seus dados (por exemplo, a senha)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Voc&ecirc definiu o valor 1 para  TEST no seu config.php, logo s&oacute ser&aacute exibido o que seria enviado',

);

?>
