<?php 
$lan = array(

  'add_list' => 'Adicionar uma lista', //duplicada em import1_text
  'cant_connect' => 'n&atildeo foi poss&iacutevel conectar &agrave base de dados',
  'no_users_to_copy' => 'Nenhum usu&aacuterio para se copiado, o prefixo est&aacute correto?',
  'remote_server' => 'Por favor, insira os dados do Servidor remoto',
  'server' => 'Servidor:',
  'user' => 'Usu&aacuterio:',
  'passwd' => 'Senha:',
  'database' => 'Nome da Base de Dados:',
  'table_prefix' => 'Prefixo da tablea:',
  'usertable_prefix' => 'Prefixo da tabela de usu&aacuterios:',
  'select_lists' => 'Selecione as listas nas quais voc&ecirc quer adicionar os emails',
  'copy_lists' => 'Copiar listas do servidor local (as listas s&atildeo encontradas atrav&eacutes do nome)',
  'users_as_html' => 'Marcar novos usu&aacuterios como HTML:',
  'info_overwrite_existing' => 'Se voc&ecirc marcar "Sobrescrever Existente", a informa&ccedil&atildeo do usu&aacuterio na base de dados ser&aacute substitu&iacuteda pela informa&ccedil&atildeo importada. Os usu&aacuterios s&atildeo encontrados atrav&eacutes do email.',
  'overwrite_existing' => 'Sobrescrever existente:',
  'connecting_remote' => 'Conectando com a base de dados remota',
  'getting_data' => 'Obtendo dados de ',
  'remote_version' => 'A vers&aacuteo remota &eacute',
  'remote_has' => 'Remote version has',
  'users' => 'usu&aacuterios',
  'lists' => 'listas',
  'copying_lists' => 'Copiando listas',
  'list' => 'Lista',
  'exists_locally' => 'localmente existente',
  'created_locally' => 'localmente criada',
  'remote_list' => 'Lista remota',
  'not_created' => 'n&atildeo criado',
  'copying_attribs' => 'Copiando atributos',
  'attrib' => 'Atributo',
  'copying_users' => 'Copiando usu&acuterios',
  'overwrite_local' => 'sobrescrevendo dados locais',
  'keep_local' => 'mantendo dados locais',
  'new_user' => '&eacute um novo usu&aacuterio',
  'no_mapped_attrib' => 'Error, no mapped attribute for',
  'no_local_list' => 'Erro, nenhuma lista local definida para',
  'No lists available' => 'Nenhuma lista dispon&iacutevel',
  'Done' => 'Conclu&iacutedo',
  'new users' => 'novos usu&aacuterios',
  'and' => 'e',
  'existing users' => 'usu&aacuterio existentes',
  'continue' => 'Continuar',

);
?>
