<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Voc&ecirc n&atildeo tem privil&eacutegios suficientes para ver esta p&aacutegina',
  'Add a user' => 'Adicionar um usu&aacuterio',
  'add user' => 'Adicionar Usu&acuterio',
  'Members of' => 'Membros de',
  'Tag all users in this page' => 'Rotular todos os usu&acuterios desta p&acutegina',
  'back to this list' => 'voltar para esta lista',
  'Download users on this list as a CSV file' => 'Baixar usu&acuterios desta lista em arquivo CSV',
  'Please enter a listid' => 'Por favor, insira a identifica&ccedil&atildeo da lista (listid)',
  'Processing' => 'Processando',
  'users were moved to' => 'os usu&aacuterios foram movidos para',
  'users were copied to' => 'os usu&aacuterios foram copiados para',
  'users were deleted from this list' => 'os usu&aacuterios foram removidos desta lista',
  'Users found, click add to add this user' => 'Usu&aacuterios encontrados, clique para Adicionar para incluri este usu&aacuterio',
  'Add' => 'Adicionar',
  'No user found with that email' => 'Nenhum usu&aacuterio com este email foi encontrado',
  'Inserting user' => 'Inserindo usu&aacuterio',
  'User added' => 'Usu&aacuterio adicionado',
  'Deleting' => 'Apagando',
  'Done' => 'Conclu&iacutedo',
  'Users on this list' => 'Usu&aacuterios desta lista',
  'Listing user' => 'Listando us&aacuterio',
  'to' => 'to',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Listando us&acuterio de 1 a 50',
  'Members' => 'Membros',
  'confirmed' => 'confirmado',
  'tag' => 'rotular',
  'del' => 'apagar',
  'Delete'=>'Apagar',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'freq&uml&ecircncia rss',
  'last sent' => '&uacuteltima enviada',
  'What to do with "Tagged" users' => 'O que fazer com os usu&aacuterios "Rotulados"',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Isso s&oacute processar&aacute os usu&aacuterios desta p&aacutegina que estejam com a op&ccedil&atildeo "R&oacutetulo" marcada',
  'delete' => 'Apagar',
  'move' => 'Mover',
  'copy' => 'Copiar',
  'nothing' => 'Nada',
  'to' => 'para', # as in destination
  'from this list' => 'desta lista',
  'What to do with all users' => 'O que fazer com todos os usu&aacuterios',
  'This will process all users on this list' => 'Isso processar&aacute todos os usu&aacuterios desta lista',
  'do it' => 'concluir',
  
  
);
?>
