<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Rodando em modo de teste, nenhum email ser&aacute envidado. Verifique seu arquivo de configura&ccedil&aatildeo.',
'The following restrictions have been set by your ISP:' => 'As seguintes restri&ccedil&oatildees foram definidas pelo seu provedor:',
'Script stage' => 'Script stage',
'Finished, Nothing to do' => 'Terminado, nada a ser feito',
'messages sent in' => 'mensagem enviada em',
'seconds' => 'segundos',
'invalid emails' => 'emails inv&aacutelidos',
'emails failed (will retry later)' => 'emails falharam (ser&aatildeo enviados mais tarde)',
'emails unconfirmed (not sent)' => 'emails n&atildeo confirmados (n&aatideo enviados)',
'Warning: script never reached stage 5' => 'Aten&ccedil&aatildeo: o script nunca chegou at&eacute o est&acutegio 5',
'This may be caused by a too slow or too busy server' => 'Isso pode ter sido causado por conta de o servidor estar muito lento ou ocupado',


'In safe mode, batches are set to a maximum of 100' => 'In safe mode, batches are set to a maximum of 100',
'Running in safe mode' => 'Rodando em modo de seguran&ccedila',
'msgs/hr' => 'msgs/hr',
'Reload required' => '&Eacute necess&acuterio Atualizar',
'Finished, All done' => 'Terminado, Tudo foi feito',
'Script finished, but not all messages have been sent yet.' => 'Script concl&iacutedo, mas nem todas as mensagens foram enviadas ainda.',
'Finished this run' => 'Finalizar este processo',
'(test)' => '(teste)',
'Would have sent' => 'Would have sent',
'(test)' => '(test)',
'Would have sent' => 'Would have sent',
'Started' => 'Started',
'Processing has been suspended by your ISP, please try again later' => 'Processing has been suspended by your ISP, please try again later',
'Sending in batches of' => 'Sending in batches of',
'emails' => 'emails',
'This batch will be' => 'This batch will be',
'emails, because in the last' => 'emails, because in the last',
'emails were sent' => 'emails enviados',
'Sending in batches of' => 'Sending in batches of',
'emails' => 'emails',
'In the last' => 'In the last',
'seconds more emails were sent' => 'seconds more emails were sent',
'than is currently allowed per batch' => 'than is currently allowed per batch',
'Sent in last run' => 'Sent in last run',
'Skipped in last run' => 'Skipped in last run',
'Processing has started,' => 'O Processamento come&ccedilou,',
'message(s) to process.' => 'Mensagens a serem processadas.',
'It is safe to click your stop button now, report will be sent by email to' => 'It is safe to click your "stop" button now, report will be sent by email to',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Your webserver is running in "safe_mode". Please keep this window open. It may reload several times to make sure all messages are sent.',
'Reports will be sent by email to' => 'Os Relat&oacuterios ser&aatildeo enviados por email para',
'Processing message' => 'Processando mensagem',
'Message' => 'Mensagem',
'is an RSS feed for' => '&eacute um RSS para',
'Looking for users' => 'Procurando usu&aacuterios',
'users apply for attributes, now checking lists' => 'users apply for attributes, now checking lists',
'No users apply for attributes' => 'No users apply for attributes',
'looking for users who can be excluded from this mailing' => 'looking for users who can be excluded from this processqueue run',
'Process Killed by other process' => 'Processo Interrompido por outro processo',
'Found them' => 'encontrados',
'to process' => 'a ser processado',
'No users to process for this batch' => 'No users to process for this batch',
'batch limit reached' => 'batch limit reached',
'Process Killed by other process' => 'Processo Interrompido por outro processo',
'Message I was working on has disappeared' => 'A Mensagem na qual eu estava trabalhando desapareceu',
'Sending' => 'Enviando',
'It took' => 'It took',
'seconds to send' => 'segundos para enviar',
'Failed sending to' => 'Erro ao enviar para',
'Unconfirmed user' => 'Usu&aacuterio n&aatildeo confirmado',
'Not sending to' => 'N&aatildeo est\&aacute sendo enviada para',
'already sent' => 'j&acute foi enviada',
'Processed' => 'Processado',
'out of' => 'fora de',
'Hmmm, No users found to send to' => 'Hmmm, N&aatildeo foi encontrado nenhum usu&aacuterio para enviar',
'It took' => 'It took',
'to send this message' => 'para mandar esta mensagem',
'waiting for' => 'Aguardando',
'to make sure we don\'t exceed our limit of' => 'assegure-se de n&aatildeo ter excedido o nosso limite de',
'messages in' => 'mensagens em',
);

?>