<?php
$lan = array(
  'Resending confirmation request to' => 'Enviando a confirma&ccedil;&atilde;o pedida para',
  'user found' => 'usu&aacute;rio encontrado',
  'no user found' => 'noi foi encontrado nenhum usu&aacute;rio',
  'unable to find original email' => 'n&atilde;o &eacute; poss&iacute;vel encontrar o email original',
  'Marking all users confirmed' => 'Marcando todos os usu&aacute;rios como confirmados',
  'users apply' => 'users apply',
  'Creating UniqID for all users who do not have one' => 'Criando UniqID para todos os usu&aacuterios que n&atildeo possuem uma',
  'Marking all users to receive HTML' => 'Marcando todos os usu&aacute;rios para receber HTML',
  'Marking all users to receive text' => 'Marcando todos os usu&aacute;rios para receber Texto',
  'Deleting users who are not on any list' => 'Apagando os usu&aacute;rios que n&atilde;o est&atilde;o em nenhuma lista',
  'Moving users who are not on any list to' => 'Mover os usu&aacute;rios que n&atilde;o est&atilde;o em nenhuma lista para',
  'Deleting users with more than' => 'Deletar os usu&aacute;rios com mais de',
  'bounces' => 'emails com problema',
  'Resending request for confirmation to users who signed up after' => 'Reenviando os pedidos de confirma&ccedil;&atilde;o para usu&aacute;rios que se inscreveram mais tarde/depois',
  'and before' => 'e antes',
  'Deleting unconfirmed users who signed up after' => 'Apagando usu&aacute;rios que n&atilde;o confirmar&atilde;o inscri&ccedil;&atilde;o despois de',
  'Trying to merge duplicates' => 'Tentando fundir duplicatas',
  'Don\'t know how to' => 'N&atilde;o se sabe como',
  'Listing users with an invalid email' => 'Listando usu&aacute;rios com email inv&aacute;lido',
  'Users deleted' => 'Usu&aacute;rio exclu&iacute;do',
  'Users apply' => 'Users apply',
  'Trying to fix users with an invalid email' => 'Tentando corrigir usu&aacute;rios com email inv&aacute;lidos',
  'User' => 'Usu&aacute;rio',
  'Users fixed' => 'Usu&aacute;rios corrigidos',
  'Users could not be fixed' => 'Usu&aacute;rios n&aacute;o puderam ser corrigidos',
  'Deleting users with an invalid email' => 'Apagando usu&aacute;rios com email inv&aacute;lido',
  'Marking users with an invalid email as unconfirmed' => 'Marcando usu&aacute;rios com email inv&aacute;lido como n&aacute;o confirmado',
  'Users updated' => 'Usu&aacute;rios atualizados',
  'Cleaning some user tables of invalid entries' => 'Limpando alCleaning some user tables of invalid entries',
  'entries apply' => 'entries apply',
  'Delete will delete user and all listmemberships' => 'Apagar exclu&iacute;ra o usu&aacute;rio e de todas as listas em que &eacute; membro',
  'Done' => 'Concl&iacute;do',
  'Users' => 'Usu&aacute;rios',
  'found' => 'Encontrados',
  'in the database' => 'no banco de dados',
  'Delete all users who are not subscribed to any list' => 'Apagando todos os usu&aacute;rios que n&aacute;o est&aacute;o inscritos em nenhuma lista',
  # next two are one sentence
  'To try to (automatically)' => 'Tentar (automaticamente)',
  'Find users who have an invalid email' => 'Encontrar usu&aacute;rios que t&ecirc;m email inv&aacute;lidos',
  'Make sure that all users have a UniqID' => 'Assegurar-se que todos os usu&aacute;rios tenham somente um &uacute;nico ID',
  'Mark all users with an invalid email as unconfirmed' => 'Marcar todos usu&aacute;rios com email inv&aacute;lido como n&atilde;o confirmado',
  'Delete users who have an invalid email' => 'Apagar usu&aacute;rios que tenham email inv&aacute;lido',
  'Mark all users to receive HTML' => 'Marcar que todos os usu&aacute;rios para que recebam mensagens tipo HTML',
  'Mark all users to receive text' => 'Marcar que todos os usu&aacute;rios para que recebam mensagens tipo Texto',
  'Mark all users confirmed' => 'Marcar todos usu&aacute;rios como confirmado',
  'Fix emails for users who have an invalid email' => 'Corrigir emails de usu&aacute;rios que tenham email inv&aacute;lido',
  'Remove Stale entries from the database' => 'Remove Stale entries from the database',
  'Merge Duplicate Users' => 'Fundir Usu&aacute;rios Duplicados',  
  'To move all users who are not subscribed to any list to' => 'Mover todos usu&aacute;rios que n&atilde;o est&atilde;o inscritos em nenhuma lista para',
  'Click here' => 'Clique aqui',
  'To delete all users with more than' => 'Apagar todos usu&aacute;rios com mais de',
  'bounces' => 'emails com problema',
  'Note: this will use the total count of bounces on a user, not consecutive bounces' => 'Aten&ccedil;&atilde;o: isso usu&aacute;ra o n&uacute;mero total de emails com problema de um usu&aacute;rio, n&atilde;o de emails com problemas consecutivosthis will use the total count of bounces on a user, not consecutive bounces',
  'To resend the request for confirmation to users who signed up and have not confirmed their subscription' => 'Reenviar pedido de confirma&ccedil&atilde;o para usu&aacute;rios que se conectaram, mas n&atilde;o confirmaram sua inscri&cceil;&atilde;o',
  'Date they signed up after' => 'Date they signed up after',
  'Date they signed up before' => 'Date they signed up before',
  'Text to prepend to email' => 'Text to prepend to email',
  'prependemailtext' => '
Desculpe o inc&ocirc;modo: estamos limpando nossa base de dados e aparece voc&ecirc; se inscreveu em nossas listas e n&atilde;o confirmou a sua inscri&ccedil;&atilde;o.

N&oacute;s gostar&iacute;amos de dar-le una nova oportunidade para reconfirmar a sua inscri&ccedil;&atilde;o. As instru&ccedil;&otilde;es de como confirm&aacute;-la segue abaixo:  ',
  'To delete users who signed up and have not confirmed their subscription' => 'Apagar usu&aacute;rios que se conectaram, mas que n&atilde;o confirmaram sua inscri&ccedil;&atilde;o',
  

);
?>
