
<!-- footer starts -->
 </td>
</tr>
</table>
<!--INNER TABLE holding nav and main body ends-->
</td>
<td background="images/rightside.png"><img src="images/rightside.png" width=27 height=1 hspace=0 vspace=0 border=0 alt=""></td>
</tr>
</table>
<!--MAIN TABLE ends-->
<!--BOTTOM TABLE starts here-->
<table width=626 border=0 cellpadding=0 cellspacing=0>
<tr>
<td><img src="images/bot_01.png" width=136 height=20 hspace=0 vspace=0 border=0 alt=""></td>
<td><img src="images/orangebit.png" width=16 height=20 hspace=0 vspace=0 border=0 align="left" alt=""></td>
<td colspan="2"><img src="images/spacer.png" width=372 height=1 hspace=0 vspace=0 border=0 alt=""></td>
<td><img src="images/bot_02.png" width=36 height=20 hspace=0 vspace=0 border=0 alt=""></td>
</tr>
<tr>
<td colspan="5"><img src="images/bot_03.png" width=626 height=9 hspace=0 vspace=0 border=0 alt=""></td>
</tr>
<tr>
<td><img src="images/bot_04.png" width=136 height=25 hspace=0 vspace=0 border=0 alt=""></td>
<td><img src="images/bot_05.png" width=82 height=25 hspace=0 vspace=0 border=0 alt=""></td>
<!--EDITABLE TEXT PART of bottom bar goes in here-->
<td bgcolor="#339933" align="center" class="botbartd"><img src="images/spacer.png" width=213 height=1 hspace=0 vspace=0 border=0 alt=""><br><span class="botbar">&copy; <a href="http://www.tincan.co.uk" target="_tincan" class="url">tincan limited</a> | <a href="http://www.phplist.com" class="url" target="phplist">php list</a> v <?php echo VERSION?></span></td>
<td><img src="images/bot_07.png" width=159 height=25 hspace=0 vspace=0 border=0 alt=""></td>
<td><img src="images/bot_08.png" width=36 height=25 hspace=0 vspace=0 border=0 alt=""></td>
</tr>
<tr>
<td colspan="5"><img src="images/bot_09.png" width=626 height=11 hspace=0 vspace=0 border=0 alt=""></td>
</tr>
</table><!--BOTTOM TABLE ends here-->


</div>

</body>
</html>
body>
</html>
